### VCS (Version Control System) API Tests
### Tests for VcsController endpoints
### Uses {{baseUrl}} from http-client.env.json

### Get VCS information
GET {{baseUrl}}/api/vcs
Content-Type: application/json

> {%
  client.assert(response.status === 200, "VCS info should return 200");
  client.log("VCS info retrieved");
%}
