/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * AgentConfig
 */
@JsonPropertyOrder({
        AgentConfig.JSON_PROPERTY_MODEL,
        AgentConfig.JSON_PROPERTY_VARIANT,
        AgentConfig.JSON_PROPERTY_TEMPERATURE,
        AgentConfig.JSON_PROPERTY_TOP_P,
        AgentConfig.JSON_PROPERTY_PROMPT,
        AgentConfig.JSON_PROPERTY_TOOLS,
        AgentConfig.JSON_PROPERTY_DISABLE,
        AgentConfig.JSON_PROPERTY_DESCRIPTION,
        AgentConfig.JSON_PROPERTY_MODE,
        AgentConfig.JSON_PROPERTY_HIDDEN,
        AgentConfig.JSON_PROPERTY_OPTIONS,
        AgentConfig.JSON_PROPERTY_COLOR,
        AgentConfig.JSON_PROPERTY_STEPS,
        AgentConfig.JSON_PROPERTY_MAX_STEPS,
        AgentConfig.JSON_PROPERTY_PERMISSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class AgentConfig {
    public static final String JSON_PROPERTY_MODEL = "model";
    @jakarta.annotation.Nullable
    private String model;

    public static final String JSON_PROPERTY_VARIANT = "variant";
    @jakarta.annotation.Nullable
    private String variant;

    public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
    @jakarta.annotation.Nullable
    private BigDecimal temperature;

    public static final String JSON_PROPERTY_TOP_P = "top_p";
    @jakarta.annotation.Nullable
    private BigDecimal topP;

    public static final String JSON_PROPERTY_PROMPT = "prompt";
    @jakarta.annotation.Nullable
    private String prompt;

    public static final String JSON_PROPERTY_TOOLS = "tools";
    @jakarta.annotation.Nullable
    private Map<String, Boolean> tools = new HashMap<>();

    public static final String JSON_PROPERTY_DISABLE = "disable";
    @jakarta.annotation.Nullable
    private Boolean disable;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    @jakarta.annotation.Nullable
    private String description;

    /**
     * Gets or Sets mode
     */
    public enum ModeEnum {
        SUBAGENT(String.valueOf("subagent")),

        PRIMARY(String.valueOf("primary")),

        ALL(String.valueOf("all"));

        private String value;

        ModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static ModeEnum fromValue(String value) {
            for (ModeEnum b : ModeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_MODE = "mode";
    @jakarta.annotation.Nullable
    private ModeEnum mode;

    public static final String JSON_PROPERTY_HIDDEN = "hidden";
    @jakarta.annotation.Nullable
    private Boolean hidden;

    public static final String JSON_PROPERTY_OPTIONS = "options";
    @jakarta.annotation.Nullable
    private Map<String, Object> options = new HashMap<>();

    public static final String JSON_PROPERTY_COLOR = "color";
    @jakarta.annotation.Nullable
    private AgentConfigColor color;

    public static final String JSON_PROPERTY_STEPS = "steps";
    @jakarta.annotation.Nullable
    private Integer steps;

    public static final String JSON_PROPERTY_MAX_STEPS = "maxSteps";
    @jakarta.annotation.Nullable
    private Integer maxSteps;

    public static final String JSON_PROPERTY_PERMISSION = "permission";
    @jakarta.annotation.Nullable
    private PermissionConfig permission;

    public AgentConfig() {
    }

    public AgentConfig model(@jakarta.annotation.Nullable String model) {
        this.model = model;
        return this;
    }

    /**
     * Get model
     *
     * @return model
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getModel() {
        return model;
    }


    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModel(@jakarta.annotation.Nullable String model) {
        this.model = model;
    }


    public AgentConfig variant(@jakarta.annotation.Nullable String variant) {
        this.variant = variant;
        return this;
    }

    /**
     * Default model variant for this agent (applies only when using the agent&#39;s configured model).
     *
     * @return variant
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getVariant() {
        return variant;
    }


    @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVariant(@jakarta.annotation.Nullable String variant) {
        this.variant = variant;
    }


    public AgentConfig temperature(@jakarta.annotation.Nullable BigDecimal temperature) {
        this.temperature = temperature;
        return this;
    }

    /**
     * Get temperature
     *
     * @return temperature
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public BigDecimal getTemperature() {
        return temperature;
    }


    @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTemperature(@jakarta.annotation.Nullable BigDecimal temperature) {
        this.temperature = temperature;
    }


    public AgentConfig topP(@jakarta.annotation.Nullable BigDecimal topP) {
        this.topP = topP;
        return this;
    }

    /**
     * Get topP
     *
     * @return topP
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_TOP_P, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public BigDecimal getTopP() {
        return topP;
    }


    @JsonProperty(value = JSON_PROPERTY_TOP_P, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTopP(@jakarta.annotation.Nullable BigDecimal topP) {
        this.topP = topP;
    }


    public AgentConfig prompt(@jakarta.annotation.Nullable String prompt) {
        this.prompt = prompt;
        return this;
    }

    /**
     * Get prompt
     *
     * @return prompt
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_PROMPT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getPrompt() {
        return prompt;
    }


    @JsonProperty(value = JSON_PROPERTY_PROMPT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrompt(@jakarta.annotation.Nullable String prompt) {
        this.prompt = prompt;
    }


    public AgentConfig tools(@jakarta.annotation.Nullable Map<String, Boolean> tools) {
        this.tools = tools;
        return this;
    }

    public AgentConfig putToolsItem(String key, Boolean toolsItem) {
        if (this.tools == null) {
            this.tools = new HashMap<>();
        }
        this.tools.put(key, toolsItem);
        return this;
    }

    /**
     * @return tools
     * @deprecated Use &#39;permission&#39; field instead
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, Boolean> getTools() {
        return tools;
    }


    @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTools(@jakarta.annotation.Nullable Map<String, Boolean> tools) {
        this.tools = tools;
    }


    public AgentConfig disable(@jakarta.annotation.Nullable Boolean disable) {
        this.disable = disable;
        return this;
    }

    /**
     * Get disable
     *
     * @return disable
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_DISABLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getDisable() {
        return disable;
    }


    @JsonProperty(value = JSON_PROPERTY_DISABLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisable(@jakarta.annotation.Nullable Boolean disable) {
        this.disable = disable;
    }


    public AgentConfig description(@jakarta.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Description of when to use the agent
     *
     * @return description
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDescription() {
        return description;
    }


    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDescription(@jakarta.annotation.Nullable String description) {
        this.description = description;
    }


    public AgentConfig mode(@jakarta.annotation.Nullable ModeEnum mode) {
        this.mode = mode;
        return this;
    }

    /**
     * Get mode
     *
     * @return mode
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ModeEnum getMode() {
        return mode;
    }


    @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMode(@jakarta.annotation.Nullable ModeEnum mode) {
        this.mode = mode;
    }


    public AgentConfig hidden(@jakarta.annotation.Nullable Boolean hidden) {
        this.hidden = hidden;
        return this;
    }

    /**
     * Hide this subagent from the @ autocomplete menu (default: false, only applies to mode: subagent)
     *
     * @return hidden
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_HIDDEN, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getHidden() {
        return hidden;
    }


    @JsonProperty(value = JSON_PROPERTY_HIDDEN, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHidden(@jakarta.annotation.Nullable Boolean hidden) {
        this.hidden = hidden;
    }


    public AgentConfig options(@jakarta.annotation.Nullable Map<String, Object> options) {
        this.options = options;
        return this;
    }

    public AgentConfig putOptionsItem(String key, Object optionsItem) {
        if (this.options == null) {
            this.options = new HashMap<>();
        }
        this.options.put(key, optionsItem);
        return this;
    }

    /**
     * Get options
     *
     * @return options
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = false)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, Object> getOptions() {
        return options;
    }


    @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = false)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public void setOptions(@jakarta.annotation.Nullable Map<String, Object> options) {
        this.options = options;
    }


    public AgentConfig color(@jakarta.annotation.Nullable AgentConfigColor color) {
        this.color = color;
        return this;
    }

    /**
     * Get color
     *
     * @return color
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfigColor getColor() {
        return color;
    }


    @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setColor(@jakarta.annotation.Nullable AgentConfigColor color) {
        this.color = color;
    }


    public AgentConfig steps(@jakarta.annotation.Nullable Integer steps) {
        this.steps = steps;
        return this;
    }

    /**
     * Maximum number of agentic iterations before forcing text-only response
     * minimum: 0
     * maximum: 9007199254740991
     *
     * @return steps
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_STEPS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getSteps() {
        return steps;
    }


    @JsonProperty(value = JSON_PROPERTY_STEPS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSteps(@jakarta.annotation.Nullable Integer steps) {
        this.steps = steps;
    }


    public AgentConfig maxSteps(@jakarta.annotation.Nullable Integer maxSteps) {
        this.maxSteps = maxSteps;
        return this;
    }

    /**
     * @return maxSteps
     * @deprecated Use &#39;steps&#39; field instead.
     * minimum: 0
     * maximum: 9007199254740991
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MAX_STEPS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getMaxSteps() {
        return maxSteps;
    }


    @JsonProperty(value = JSON_PROPERTY_MAX_STEPS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxSteps(@jakarta.annotation.Nullable Integer maxSteps) {
        this.maxSteps = maxSteps;
    }


    public AgentConfig permission(@jakarta.annotation.Nullable PermissionConfig permission) {
        this.permission = permission;
        return this;
    }

    /**
     * Get permission
     *
     * @return permission
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_PERMISSION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PermissionConfig getPermission() {
        return permission;
    }


    @JsonProperty(value = JSON_PROPERTY_PERMISSION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPermission(@jakarta.annotation.Nullable PermissionConfig permission) {
        this.permission = permission;
    }

    /**
     * A container for additional, undeclared properties.
     * This is a holder for any undeclared properties as specified with
     * the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value.
     * If the property does not already exist, create it otherwise replace it.
     *
     * @param key   the name of the property
     * @param value the value of the property
     * @return self reference
     */
    @JsonAnySetter
    public AgentConfig putAdditionalProperty(String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
     * Return the additional (undeclared) properties.
     *
     * @return the additional (undeclared) properties
     */
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key the name of the property
     * @return the additional (undeclared) property with the specified name
     */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    /**
     * Return true if this AgentConfig object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgentConfig agentConfig = (AgentConfig) o;
        return Objects.equals(this.model, agentConfig.model) &&
                Objects.equals(this.variant, agentConfig.variant) &&
                Objects.equals(this.temperature, agentConfig.temperature) &&
                Objects.equals(this.topP, agentConfig.topP) &&
                Objects.equals(this.prompt, agentConfig.prompt) &&
                Objects.equals(this.tools, agentConfig.tools) &&
                Objects.equals(this.disable, agentConfig.disable) &&
                Objects.equals(this.description, agentConfig.description) &&
                Objects.equals(this.mode, agentConfig.mode) &&
                Objects.equals(this.hidden, agentConfig.hidden) &&
                Objects.equals(this.options, agentConfig.options) &&
                Objects.equals(this.color, agentConfig.color) &&
                Objects.equals(this.steps, agentConfig.steps) &&
                Objects.equals(this.maxSteps, agentConfig.maxSteps) &&
                Objects.equals(this.permission, agentConfig.permission) &&
                Objects.equals(this.additionalProperties, agentConfig.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(model, variant, temperature, topP, prompt, tools, disable, description, mode, hidden, options, color, steps, maxSteps, permission, additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AgentConfig {\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
        sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
        sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
        sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
        sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
        sb.append("    disable: ").append(toIndentedString(disable)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
        sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
        sb.append("    options: ").append(toIndentedString(options)).append("\n");
        sb.append("    color: ").append(toIndentedString(color)).append("\n");
        sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
        sb.append("    maxSteps: ").append(toIndentedString(maxSteps)).append("\n");
        sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
        sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `model` to the URL query string
        if (getModel() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
        }

        // add `variant` to the URL query string
        if (getVariant() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%svariant%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVariant()))));
        }

        // add `temperature` to the URL query string
        if (getTemperature() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%stemperature%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemperature()))));
        }

        // add `top_p` to the URL query string
        if (getTopP() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%stop_p%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTopP()))));
        }

        // add `prompt` to the URL query string
        if (getPrompt() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sprompt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrompt()))));
        }

        // add `tools` to the URL query string
        if (getTools() != null) {
            for (String _key : getTools().keySet()) {
                joiner.add(String.format(java.util.Locale.ROOT, "%stools%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
                        getTools().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getTools().get(_key)))));
            }
        }

        // add `disable` to the URL query string
        if (getDisable() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdisable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisable()))));
        }

        // add `description` to the URL query string
        if (getDescription() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
        }

        // add `mode` to the URL query string
        if (getMode() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMode()))));
        }

        // add `hidden` to the URL query string
        if (getHidden() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%shidden%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHidden()))));
        }

        // add `options` to the URL query string
        if (getOptions() != null) {
            for (String _key : getOptions().keySet()) {
                joiner.add(String.format(java.util.Locale.ROOT, "%soptions%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
                        getOptions().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getOptions().get(_key)))));
            }
        }

        // add `color` to the URL query string
        if (getColor() != null) {
            joiner.add(getColor().toUrlQueryString(prefix + "color" + suffix));
        }

        // add `steps` to the URL query string
        if (getSteps() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%ssteps%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSteps()))));
        }

        // add `maxSteps` to the URL query string
        if (getMaxSteps() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smaxSteps%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxSteps()))));
        }

        // add `permission` to the URL query string
        if (getPermission() != null) {
            joiner.add(getPermission().toUrlQueryString(prefix + "permission" + suffix));
        }

        return joiner.toString();
    }
}

