/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * AppSkills200ResponseInner
 */
@JsonPropertyOrder({
        AppSkills200ResponseInner.JSON_PROPERTY_NAME,
        AppSkills200ResponseInner.JSON_PROPERTY_DESCRIPTION,
        AppSkills200ResponseInner.JSON_PROPERTY_LOCATION,
        AppSkills200ResponseInner.JSON_PROPERTY_CONTENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class AppSkills200ResponseInner {
    public static final String JSON_PROPERTY_NAME = "name";
    @jakarta.annotation.Nonnull
    private String name;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    @jakarta.annotation.Nonnull
    private String description;

    public static final String JSON_PROPERTY_LOCATION = "location";
    @jakarta.annotation.Nonnull
    private String location;

    public static final String JSON_PROPERTY_CONTENT = "content";
    @jakarta.annotation.Nonnull
    private String content;

    public AppSkills200ResponseInner() {
    }

    public AppSkills200ResponseInner name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getName() {
        return name;
    }


    @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }


    public AppSkills200ResponseInner description(@jakarta.annotation.Nonnull String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getDescription() {
        return description;
    }


    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDescription(@jakarta.annotation.Nonnull String description) {
        this.description = description;
    }


    public AppSkills200ResponseInner location(@jakarta.annotation.Nonnull String location) {
        this.location = location;
        return this;
    }

    /**
     * Get location
     *
     * @return location
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getLocation() {
        return location;
    }


    @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocation(@jakarta.annotation.Nonnull String location) {
        this.location = location;
    }


    public AppSkills200ResponseInner content(@jakarta.annotation.Nonnull String content) {
        this.content = content;
        return this;
    }

    /**
     * Get content
     *
     * @return content
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getContent() {
        return content;
    }


    @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setContent(@jakarta.annotation.Nonnull String content) {
        this.content = content;
    }


    /**
     * Return true if this app_skills_200_response_inner object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AppSkills200ResponseInner appSkills200ResponseInner = (AppSkills200ResponseInner) o;
        return Objects.equals(this.name, appSkills200ResponseInner.name) &&
                Objects.equals(this.description, appSkills200ResponseInner.description) &&
                Objects.equals(this.location, appSkills200ResponseInner.location) &&
                Objects.equals(this.content, appSkills200ResponseInner.content);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, location, content);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AppSkills200ResponseInner {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    location: ").append(toIndentedString(location)).append("\n");
        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `name` to the URL query string
        if (getName() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
        }

        // add `description` to the URL query string
        if (getDescription() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
        }

        // add `location` to the URL query string
        if (getLocation() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%slocation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocation()))));
        }

        // add `content` to the URL query string
        if (getContent() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
        }

        return joiner.toString();
    }
}

