/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Command
 */
@JsonPropertyOrder({
        Command.JSON_PROPERTY_NAME,
        Command.JSON_PROPERTY_DESCRIPTION,
        Command.JSON_PROPERTY_AGENT,
        Command.JSON_PROPERTY_MODEL,
        Command.JSON_PROPERTY_SOURCE,
        Command.JSON_PROPERTY_TEMPLATE,
        Command.JSON_PROPERTY_SUBTASK,
        Command.JSON_PROPERTY_HINTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class Command {
    public static final String JSON_PROPERTY_NAME = "name";
    @jakarta.annotation.Nonnull
    private String name;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    @jakarta.annotation.Nullable
    private String description;

    public static final String JSON_PROPERTY_AGENT = "agent";
    @jakarta.annotation.Nullable
    private String agent;

    public static final String JSON_PROPERTY_MODEL = "model";
    @jakarta.annotation.Nullable
    private String model;

    /**
     * Gets or Sets source
     */
    public enum SourceEnum {
        COMMAND(String.valueOf("command")),

        MCP(String.valueOf("mcp")),

        SKILL(String.valueOf("skill"));

        private String value;

        SourceEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static SourceEnum fromValue(String value) {
            for (SourceEnum b : SourceEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_SOURCE = "source";
    @jakarta.annotation.Nullable
    private SourceEnum source;

    public static final String JSON_PROPERTY_TEMPLATE = "template";
    @jakarta.annotation.Nonnull
    private CommandTemplate template;

    public static final String JSON_PROPERTY_SUBTASK = "subtask";
    @jakarta.annotation.Nullable
    private Boolean subtask;

    public static final String JSON_PROPERTY_HINTS = "hints";
    @jakarta.annotation.Nonnull
    private List<String> hints = new ArrayList<>();

    public Command() {
    }

    public Command name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getName() {
        return name;
    }


    @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }


    public Command description(@jakarta.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDescription() {
        return description;
    }


    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDescription(@jakarta.annotation.Nullable String description) {
        this.description = description;
    }


    public Command agent(@jakarta.annotation.Nullable String agent) {
        this.agent = agent;
        return this;
    }

    /**
     * Get agent
     *
     * @return agent
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getAgent() {
        return agent;
    }


    @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAgent(@jakarta.annotation.Nullable String agent) {
        this.agent = agent;
    }


    public Command model(@jakarta.annotation.Nullable String model) {
        this.model = model;
        return this;
    }

    /**
     * Get model
     *
     * @return model
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getModel() {
        return model;
    }


    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModel(@jakarta.annotation.Nullable String model) {
        this.model = model;
    }


    public Command source(@jakarta.annotation.Nullable SourceEnum source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     *
     * @return source
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public SourceEnum getSource() {
        return source;
    }


    @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSource(@jakarta.annotation.Nullable SourceEnum source) {
        this.source = source;
    }


    public Command template(@jakarta.annotation.Nonnull CommandTemplate template) {
        this.template = template;
        return this;
    }

    /**
     * Get template
     *
     * @return template
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public CommandTemplate getTemplate() {
        return template;
    }


    @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTemplate(@jakarta.annotation.Nonnull CommandTemplate template) {
        this.template = template;
    }


    public Command subtask(@jakarta.annotation.Nullable Boolean subtask) {
        this.subtask = subtask;
        return this;
    }

    /**
     * Get subtask
     *
     * @return subtask
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_SUBTASK, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getSubtask() {
        return subtask;
    }


    @JsonProperty(value = JSON_PROPERTY_SUBTASK, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubtask(@jakarta.annotation.Nullable Boolean subtask) {
        this.subtask = subtask;
    }


    public Command hints(@jakarta.annotation.Nonnull List<String> hints) {
        this.hints = hints;
        return this;
    }

    public Command addHintsItem(String hintsItem) {
        if (this.hints == null) {
            this.hints = new ArrayList<>();
        }
        this.hints.add(hintsItem);
        return this;
    }

    /**
     * Get hints
     *
     * @return hints
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_HINTS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<String> getHints() {
        return hints;
    }


    @JsonProperty(value = JSON_PROPERTY_HINTS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHints(@jakarta.annotation.Nonnull List<String> hints) {
        this.hints = hints;
    }


    /**
     * Return true if this Command object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Command command = (Command) o;
        return Objects.equals(this.name, command.name) &&
                Objects.equals(this.description, command.description) &&
                Objects.equals(this.agent, command.agent) &&
                Objects.equals(this.model, command.model) &&
                Objects.equals(this.source, command.source) &&
                Objects.equals(this.template, command.template) &&
                Objects.equals(this.subtask, command.subtask) &&
                Objects.equals(this.hints, command.hints);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, agent, model, source, template, subtask, hints);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Command {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    template: ").append(toIndentedString(template)).append("\n");
        sb.append("    subtask: ").append(toIndentedString(subtask)).append("\n");
        sb.append("    hints: ").append(toIndentedString(hints)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `name` to the URL query string
        if (getName() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
        }

        // add `description` to the URL query string
        if (getDescription() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
        }

        // add `agent` to the URL query string
        if (getAgent() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sagent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgent()))));
        }

        // add `model` to the URL query string
        if (getModel() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
        }

        // add `source` to the URL query string
        if (getSource() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%ssource%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSource()))));
        }

        // add `template` to the URL query string
        if (getTemplate() != null) {
            joiner.add(getTemplate().toUrlQueryString(prefix + "template" + suffix));
        }

        // add `subtask` to the URL query string
        if (getSubtask() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%ssubtask%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubtask()))));
        }

        // add `hints` to the URL query string
        if (getHints() != null) {
            for (int i = 0; i < getHints().size(); i++) {
                joiner.add(String.format(java.util.Locale.ROOT, "%shints%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
                        ApiClient.urlEncode(ApiClient.valueToString(getHints().get(i)))));
            }
        }

        return joiner.toString();
    }
}

