/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * ConfigExperimental
 */
@JsonPropertyOrder({
  ConfigExperimental.JSON_PROPERTY_DISABLE_PASTE_SUMMARY,
  ConfigExperimental.JSON_PROPERTY_BATCH_TOOL,
  ConfigExperimental.JSON_PROPERTY_OPEN_TELEMETRY,
  ConfigExperimental.JSON_PROPERTY_PRIMARY_TOOLS,
  ConfigExperimental.JSON_PROPERTY_CONTINUE_LOOP_ON_DENY,
  ConfigExperimental.JSON_PROPERTY_MCP_TIMEOUT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ConfigExperimental {
  public static final String JSON_PROPERTY_DISABLE_PASTE_SUMMARY = "disable_paste_summary";
  @jakarta.annotation.Nullable
  private Boolean disablePasteSummary;

  public static final String JSON_PROPERTY_BATCH_TOOL = "batch_tool";
  @jakarta.annotation.Nullable
  private Boolean batchTool;

  public static final String JSON_PROPERTY_OPEN_TELEMETRY = "openTelemetry";
  @jakarta.annotation.Nullable
  private Boolean openTelemetry;

  public static final String JSON_PROPERTY_PRIMARY_TOOLS = "primary_tools";
  @jakarta.annotation.Nullable
  private List<String> primaryTools = new ArrayList<>();

  public static final String JSON_PROPERTY_CONTINUE_LOOP_ON_DENY = "continue_loop_on_deny";
  @jakarta.annotation.Nullable
  private Boolean continueLoopOnDeny;

  public static final String JSON_PROPERTY_MCP_TIMEOUT = "mcp_timeout";
  @jakarta.annotation.Nullable
  private Integer mcpTimeout;

  public ConfigExperimental() { 
  }

  public ConfigExperimental disablePasteSummary(@jakarta.annotation.Nullable Boolean disablePasteSummary) {
    this.disablePasteSummary = disablePasteSummary;
    return this;
  }

  /**
   * Get disablePasteSummary
   * @return disablePasteSummary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISABLE_PASTE_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDisablePasteSummary() {
    return disablePasteSummary;
  }


  @JsonProperty(value = JSON_PROPERTY_DISABLE_PASTE_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisablePasteSummary(@jakarta.annotation.Nullable Boolean disablePasteSummary) {
    this.disablePasteSummary = disablePasteSummary;
  }


  public ConfigExperimental batchTool(@jakarta.annotation.Nullable Boolean batchTool) {
    this.batchTool = batchTool;
    return this;
  }

  /**
   * Enable the batch tool
   * @return batchTool
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BATCH_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getBatchTool() {
    return batchTool;
  }


  @JsonProperty(value = JSON_PROPERTY_BATCH_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchTool(@jakarta.annotation.Nullable Boolean batchTool) {
    this.batchTool = batchTool;
  }


  public ConfigExperimental openTelemetry(@jakarta.annotation.Nullable Boolean openTelemetry) {
    this.openTelemetry = openTelemetry;
    return this;
  }

  /**
   * Enable OpenTelemetry spans for AI SDK calls (using the &#39;experimental_telemetry&#39; flag)
   * @return openTelemetry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN_TELEMETRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOpenTelemetry() {
    return openTelemetry;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN_TELEMETRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenTelemetry(@jakarta.annotation.Nullable Boolean openTelemetry) {
    this.openTelemetry = openTelemetry;
  }


  public ConfigExperimental primaryTools(@jakarta.annotation.Nullable List<String> primaryTools) {
    this.primaryTools = primaryTools;
    return this;
  }

  public ConfigExperimental addPrimaryToolsItem(String primaryToolsItem) {
    if (this.primaryTools == null) {
      this.primaryTools = new ArrayList<>();
    }
    this.primaryTools.add(primaryToolsItem);
    return this;
  }

  /**
   * Tools that should only be available to primary agents.
   * @return primaryTools
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIMARY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPrimaryTools() {
    return primaryTools;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIMARY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrimaryTools(@jakarta.annotation.Nullable List<String> primaryTools) {
    this.primaryTools = primaryTools;
  }


  public ConfigExperimental continueLoopOnDeny(@jakarta.annotation.Nullable Boolean continueLoopOnDeny) {
    this.continueLoopOnDeny = continueLoopOnDeny;
    return this;
  }

  /**
   * Continue the agent loop when a tool call is denied
   * @return continueLoopOnDeny
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTINUE_LOOP_ON_DENY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContinueLoopOnDeny() {
    return continueLoopOnDeny;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTINUE_LOOP_ON_DENY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContinueLoopOnDeny(@jakarta.annotation.Nullable Boolean continueLoopOnDeny) {
    this.continueLoopOnDeny = continueLoopOnDeny;
  }


  public ConfigExperimental mcpTimeout(@jakarta.annotation.Nullable Integer mcpTimeout) {
    this.mcpTimeout = mcpTimeout;
    return this;
  }

  /**
   * Timeout in milliseconds for model context protocol (MCP) requests
   * minimum: 0
   * maximum: 9007199254740991
   * @return mcpTimeout
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MCP_TIMEOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMcpTimeout() {
    return mcpTimeout;
  }


  @JsonProperty(value = JSON_PROPERTY_MCP_TIMEOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMcpTimeout(@jakarta.annotation.Nullable Integer mcpTimeout) {
    this.mcpTimeout = mcpTimeout;
  }


  /**
   * Return true if this Config_experimental object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigExperimental configExperimental = (ConfigExperimental) o;
    return Objects.equals(this.disablePasteSummary, configExperimental.disablePasteSummary) &&
        Objects.equals(this.batchTool, configExperimental.batchTool) &&
        Objects.equals(this.openTelemetry, configExperimental.openTelemetry) &&
        Objects.equals(this.primaryTools, configExperimental.primaryTools) &&
        Objects.equals(this.continueLoopOnDeny, configExperimental.continueLoopOnDeny) &&
        Objects.equals(this.mcpTimeout, configExperimental.mcpTimeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disablePasteSummary, batchTool, openTelemetry, primaryTools, continueLoopOnDeny, mcpTimeout);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigExperimental {\n");
    sb.append("    disablePasteSummary: ").append(toIndentedString(disablePasteSummary)).append("\n");
    sb.append("    batchTool: ").append(toIndentedString(batchTool)).append("\n");
    sb.append("    openTelemetry: ").append(toIndentedString(openTelemetry)).append("\n");
    sb.append("    primaryTools: ").append(toIndentedString(primaryTools)).append("\n");
    sb.append("    continueLoopOnDeny: ").append(toIndentedString(continueLoopOnDeny)).append("\n");
    sb.append("    mcpTimeout: ").append(toIndentedString(mcpTimeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `disable_paste_summary` to the URL query string
    if (getDisablePasteSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisable_paste_summary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisablePasteSummary()))));
    }

    // add `batch_tool` to the URL query string
    if (getBatchTool() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbatch_tool%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBatchTool()))));
    }

    // add `openTelemetry` to the URL query string
    if (getOpenTelemetry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopenTelemetry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpenTelemetry()))));
    }

    // add `primary_tools` to the URL query string
    if (getPrimaryTools() != null) {
      for (int i = 0; i < getPrimaryTools().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprimary_tools%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPrimaryTools().get(i)))));
      }
    }

    // add `continue_loop_on_deny` to the URL query string
    if (getContinueLoopOnDeny() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontinue_loop_on_deny%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContinueLoopOnDeny()))));
    }

    // add `mcp_timeout` to the URL query string
    if (getMcpTimeout() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smcp_timeout%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMcpTimeout()))));
    }

    return joiner.toString();
  }
}

