/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * ConfigLspAnyOfValueAnyOf
 */
@JsonPropertyOrder({
        ConfigLspAnyOfValueAnyOf.JSON_PROPERTY_DISABLED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ConfigLspAnyOfValueAnyOf {
    /**
     * Gets or Sets disabled
     */
    public enum DisabledEnum {
        TRUE(Boolean.valueOf("true"));

        private Boolean value;

        DisabledEnum(Boolean value) {
            this.value = value;
        }

        @JsonValue
        public Boolean getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static DisabledEnum fromValue(Boolean value) {
            for (DisabledEnum b : DisabledEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_DISABLED = "disabled";
    @jakarta.annotation.Nonnull
    private DisabledEnum disabled;

    public ConfigLspAnyOfValueAnyOf() {
    }

    public ConfigLspAnyOfValueAnyOf disabled(@jakarta.annotation.Nonnull DisabledEnum disabled) {
        this.disabled = disabled;
        return this;
    }

    /**
     * Get disabled
     *
     * @return disabled
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DISABLED, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public DisabledEnum getDisabled() {
        return disabled;
    }


    @JsonProperty(value = JSON_PROPERTY_DISABLED, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDisabled(@jakarta.annotation.Nonnull DisabledEnum disabled) {
        this.disabled = disabled;
    }


    /**
     * Return true if this Config_lsp_anyOf_value_anyOf object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConfigLspAnyOfValueAnyOf configLspAnyOfValueAnyOf = (ConfigLspAnyOfValueAnyOf) o;
        return Objects.equals(this.disabled, configLspAnyOfValueAnyOf.disabled);
    }

    @Override
    public int hashCode() {
        return Objects.hash(disabled);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ConfigLspAnyOfValueAnyOf {\n");
        sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `disabled` to the URL query string
        if (getDisabled() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdisabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisabled()))));
        }

        return joiner.toString();
    }
}

