/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Agent configuration, see https://opencode.ai/docs/agents
 */
@JsonPropertyOrder({
        ConfigAgent.JSON_PROPERTY_PLAN,
        ConfigAgent.JSON_PROPERTY_BUILD,
        ConfigAgent.JSON_PROPERTY_GENERAL,
        ConfigAgent.JSON_PROPERTY_EXPLORE,
        ConfigAgent.JSON_PROPERTY_TITLE,
        ConfigAgent.JSON_PROPERTY_SUMMARY,
        ConfigAgent.JSON_PROPERTY_COMPACTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ConfigAgent {
    public static final String JSON_PROPERTY_PLAN = "plan";
    @jakarta.annotation.Nullable
    private AgentConfig plan;

    public static final String JSON_PROPERTY_BUILD = "build";
    @jakarta.annotation.Nullable
    private AgentConfig build;

    public static final String JSON_PROPERTY_GENERAL = "general";
    @jakarta.annotation.Nullable
    private AgentConfig general;

    public static final String JSON_PROPERTY_EXPLORE = "explore";
    @jakarta.annotation.Nullable
    private AgentConfig explore;

    public static final String JSON_PROPERTY_TITLE = "title";
    @jakarta.annotation.Nullable
    private AgentConfig title;

    public static final String JSON_PROPERTY_SUMMARY = "summary";
    @jakarta.annotation.Nullable
    private AgentConfig summary;

    public static final String JSON_PROPERTY_COMPACTION = "compaction";
    @jakarta.annotation.Nullable
    private AgentConfig compaction;

    public ConfigAgent() {
    }

    public ConfigAgent plan(@jakarta.annotation.Nullable AgentConfig plan) {
        this.plan = plan;
        return this;
    }

    /**
     * Get plan
     *
     * @return plan
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_PLAN, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getPlan() {
        return plan;
    }


    @JsonProperty(value = JSON_PROPERTY_PLAN, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlan(@jakarta.annotation.Nullable AgentConfig plan) {
        this.plan = plan;
    }


    public ConfigAgent build(@jakarta.annotation.Nullable AgentConfig build) {
        this.build = build;
        return this;
    }

    /**
     * Get build
     *
     * @return build
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_BUILD, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getBuild() {
        return build;
    }


    @JsonProperty(value = JSON_PROPERTY_BUILD, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBuild(@jakarta.annotation.Nullable AgentConfig build) {
        this.build = build;
    }


    public ConfigAgent general(@jakarta.annotation.Nullable AgentConfig general) {
        this.general = general;
        return this;
    }

    /**
     * Get general
     *
     * @return general
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_GENERAL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getGeneral() {
        return general;
    }


    @JsonProperty(value = JSON_PROPERTY_GENERAL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGeneral(@jakarta.annotation.Nullable AgentConfig general) {
        this.general = general;
    }


    public ConfigAgent explore(@jakarta.annotation.Nullable AgentConfig explore) {
        this.explore = explore;
        return this;
    }

    /**
     * Get explore
     *
     * @return explore
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_EXPLORE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getExplore() {
        return explore;
    }


    @JsonProperty(value = JSON_PROPERTY_EXPLORE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExplore(@jakarta.annotation.Nullable AgentConfig explore) {
        this.explore = explore;
    }


    public ConfigAgent title(@jakarta.annotation.Nullable AgentConfig title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getTitle() {
        return title;
    }


    @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTitle(@jakarta.annotation.Nullable AgentConfig title) {
        this.title = title;
    }


    public ConfigAgent summary(@jakarta.annotation.Nullable AgentConfig summary) {
        this.summary = summary;
        return this;
    }

    /**
     * Get summary
     *
     * @return summary
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getSummary() {
        return summary;
    }


    @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummary(@jakarta.annotation.Nullable AgentConfig summary) {
        this.summary = summary;
    }


    public ConfigAgent compaction(@jakarta.annotation.Nullable AgentConfig compaction) {
        this.compaction = compaction;
        return this;
    }

    /**
     * Get compaction
     *
     * @return compaction
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_COMPACTION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public AgentConfig getCompaction() {
        return compaction;
    }


    @JsonProperty(value = JSON_PROPERTY_COMPACTION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCompaction(@jakarta.annotation.Nullable AgentConfig compaction) {
        this.compaction = compaction;
    }

    /**
     * A container for additional, undeclared properties.
     * This is a holder for any undeclared properties as specified with
     * the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, AgentConfig> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value.
     * If the property does not already exist, create it otherwise replace it.
     *
     * @param key   the name of the property
     * @param value the value of the property
     * @return self reference
     */
    @JsonAnySetter
    public ConfigAgent putAdditionalProperty(String key, AgentConfig value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, AgentConfig>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
     * Return the additional (undeclared) properties.
     *
     * @return the additional (undeclared) properties
     */
    @JsonAnyGetter
    public Map<String, AgentConfig> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key the name of the property
     * @return the additional (undeclared) property with the specified name
     */
    public AgentConfig getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    /**
     * Return true if this Config_agent object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConfigAgent configAgent = (ConfigAgent) o;
        return Objects.equals(this.plan, configAgent.plan) &&
                Objects.equals(this.build, configAgent.build) &&
                Objects.equals(this.general, configAgent.general) &&
                Objects.equals(this.explore, configAgent.explore) &&
                Objects.equals(this.title, configAgent.title) &&
                Objects.equals(this.summary, configAgent.summary) &&
                Objects.equals(this.compaction, configAgent.compaction) &&
                Objects.equals(this.additionalProperties, configAgent.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(plan, build, general, explore, title, summary, compaction, additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ConfigAgent {\n");
        sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
        sb.append("    build: ").append(toIndentedString(build)).append("\n");
        sb.append("    general: ").append(toIndentedString(general)).append("\n");
        sb.append("    explore: ").append(toIndentedString(explore)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
        sb.append("    compaction: ").append(toIndentedString(compaction)).append("\n");
        sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `plan` to the URL query string
        if (getPlan() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%splan%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlan()))));
        }

        // add `build` to the URL query string
        if (getBuild() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sbuild%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuild()))));
        }

        // add `general` to the URL query string
        if (getGeneral() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sgeneral%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGeneral()))));
        }

        // add `explore` to the URL query string
        if (getExplore() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sexplore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExplore()))));
        }

        // add `title` to the URL query string
        if (getTitle() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%stitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitle()))));
        }

        // add `summary` to the URL query string
        if (getSummary() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
        }

        // add `compaction` to the URL query string
        if (getCompaction() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%scompaction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompaction()))));
        }

        return joiner.toString();
    }
}

