/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.util.*;

/**
 * ConfigLspAnyOfValueAnyOf1
 */
@JsonPropertyOrder({
        ConfigLspAnyOfValueAnyOf1.JSON_PROPERTY_COMMAND,
        ConfigLspAnyOfValueAnyOf1.JSON_PROPERTY_EXTENSIONS,
        ConfigLspAnyOfValueAnyOf1.JSON_PROPERTY_DISABLED,
        ConfigLspAnyOfValueAnyOf1.JSON_PROPERTY_ENV,
        ConfigLspAnyOfValueAnyOf1.JSON_PROPERTY_INITIALIZATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ConfigLspAnyOfValueAnyOf1 {
    public static final String JSON_PROPERTY_COMMAND = "command";
    @jakarta.annotation.Nonnull
    private List<String> command = new ArrayList<>();

    public static final String JSON_PROPERTY_EXTENSIONS = "extensions";
    @jakarta.annotation.Nullable
    private List<String> extensions = new ArrayList<>();

    public static final String JSON_PROPERTY_DISABLED = "disabled";
    @jakarta.annotation.Nullable
    private Boolean disabled;

    public static final String JSON_PROPERTY_ENV = "env";
    @jakarta.annotation.Nullable
    private Map<String, String> env = new HashMap<>();

    public static final String JSON_PROPERTY_INITIALIZATION = "initialization";
    @jakarta.annotation.Nullable
    private Map<String, Object> initialization = new HashMap<>();

    public ConfigLspAnyOfValueAnyOf1() {
    }

    public ConfigLspAnyOfValueAnyOf1 command(@jakarta.annotation.Nonnull List<String> command) {
        this.command = command;
        return this;
    }

    public ConfigLspAnyOfValueAnyOf1 addCommandItem(String commandItem) {
        if (this.command == null) {
            this.command = new ArrayList<>();
        }
        this.command.add(commandItem);
        return this;
    }

    /**
     * Get command
     *
     * @return command
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<String> getCommand() {
        return command;
    }


    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCommand(@jakarta.annotation.Nonnull List<String> command) {
        this.command = command;
    }


    public ConfigLspAnyOfValueAnyOf1 extensions(@jakarta.annotation.Nullable List<String> extensions) {
        this.extensions = extensions;
        return this;
    }

    public ConfigLspAnyOfValueAnyOf1 addExtensionsItem(String extensionsItem) {
        if (this.extensions == null) {
            this.extensions = new ArrayList<>();
        }
        this.extensions.add(extensionsItem);
        return this;
    }

    /**
     * Get extensions
     *
     * @return extensions
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_EXTENSIONS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getExtensions() {
        return extensions;
    }


    @JsonProperty(value = JSON_PROPERTY_EXTENSIONS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExtensions(@jakarta.annotation.Nullable List<String> extensions) {
        this.extensions = extensions;
    }


    public ConfigLspAnyOfValueAnyOf1 disabled(@jakarta.annotation.Nullable Boolean disabled) {
        this.disabled = disabled;
        return this;
    }

    /**
     * Get disabled
     *
     * @return disabled
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_DISABLED, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getDisabled() {
        return disabled;
    }


    @JsonProperty(value = JSON_PROPERTY_DISABLED, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisabled(@jakarta.annotation.Nullable Boolean disabled) {
        this.disabled = disabled;
    }


    public ConfigLspAnyOfValueAnyOf1 env(@jakarta.annotation.Nullable Map<String, String> env) {
        this.env = env;
        return this;
    }

    public ConfigLspAnyOfValueAnyOf1 putEnvItem(String key, String envItem) {
        if (this.env == null) {
            this.env = new HashMap<>();
        }
        this.env.put(key, envItem);
        return this;
    }

    /**
     * Get env
     *
     * @return env
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_ENV, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, String> getEnv() {
        return env;
    }


    @JsonProperty(value = JSON_PROPERTY_ENV, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnv(@jakarta.annotation.Nullable Map<String, String> env) {
        this.env = env;
    }


    public ConfigLspAnyOfValueAnyOf1 initialization(@jakarta.annotation.Nullable Map<String, Object> initialization) {
        this.initialization = initialization;
        return this;
    }

    public ConfigLspAnyOfValueAnyOf1 putInitializationItem(String key, Object initializationItem) {
        if (this.initialization == null) {
            this.initialization = new HashMap<>();
        }
        this.initialization.put(key, initializationItem);
        return this;
    }

    /**
     * Get initialization
     *
     * @return initialization
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_INITIALIZATION, required = false)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, Object> getInitialization() {
        return initialization;
    }


    @JsonProperty(value = JSON_PROPERTY_INITIALIZATION, required = false)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public void setInitialization(@jakarta.annotation.Nullable Map<String, Object> initialization) {
        this.initialization = initialization;
    }


    /**
     * Return true if this Config_lsp_anyOf_value_anyOf_1 object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConfigLspAnyOfValueAnyOf1 configLspAnyOfValueAnyOf1 = (ConfigLspAnyOfValueAnyOf1) o;
        return Objects.equals(this.command, configLspAnyOfValueAnyOf1.command) &&
                Objects.equals(this.extensions, configLspAnyOfValueAnyOf1.extensions) &&
                Objects.equals(this.disabled, configLspAnyOfValueAnyOf1.disabled) &&
                Objects.equals(this.env, configLspAnyOfValueAnyOf1.env) &&
                Objects.equals(this.initialization, configLspAnyOfValueAnyOf1.initialization);
    }

    @Override
    public int hashCode() {
        return Objects.hash(command, extensions, disabled, env, initialization);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ConfigLspAnyOfValueAnyOf1 {\n");
        sb.append("    command: ").append(toIndentedString(command)).append("\n");
        sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
        sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
        sb.append("    env: ").append(toIndentedString(env)).append("\n");
        sb.append("    initialization: ").append(toIndentedString(initialization)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `command` to the URL query string
        if (getCommand() != null) {
            for (int i = 0; i < getCommand().size(); i++) {
                joiner.add(String.format(java.util.Locale.ROOT, "%scommand%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
                        ApiClient.urlEncode(ApiClient.valueToString(getCommand().get(i)))));
            }
        }

        // add `extensions` to the URL query string
        if (getExtensions() != null) {
            for (int i = 0; i < getExtensions().size(); i++) {
                joiner.add(String.format(java.util.Locale.ROOT, "%sextensions%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
                        ApiClient.urlEncode(ApiClient.valueToString(getExtensions().get(i)))));
            }
        }

        // add `disabled` to the URL query string
        if (getDisabled() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdisabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisabled()))));
        }

        // add `env` to the URL query string
        if (getEnv() != null) {
            for (String _key : getEnv().keySet()) {
                joiner.add(String.format(java.util.Locale.ROOT, "%senv%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
                        getEnv().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getEnv().get(_key)))));
            }
        }

        // add `initialization` to the URL query string
        if (getInitialization() != null) {
            for (String _key : getInitialization().keySet()) {
                joiner.add(String.format(java.util.Locale.ROOT, "%sinitialization%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
                        getInitialization().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getInitialization().get(_key)))));
            }
        }

        return joiner.toString();
    }
}

