/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * EventQuestionRejectedProperties
 */
@JsonPropertyOrder({
  EventQuestionRejectedProperties.JSON_PROPERTY_SESSION_I_D,
  EventQuestionRejectedProperties.JSON_PROPERTY_REQUEST_I_D
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class EventQuestionRejectedProperties {
  public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
  @jakarta.annotation.Nonnull
  private String sessionID;

  public static final String JSON_PROPERTY_REQUEST_I_D = "requestID";
  @jakarta.annotation.Nonnull
  private String requestID;

  public EventQuestionRejectedProperties() { 
  }

  public EventQuestionRejectedProperties sessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
    return this;
  }

  /**
   * Get sessionID
   * @return sessionID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSessionID() {
    return sessionID;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
  }


  public EventQuestionRejectedProperties requestID(@jakarta.annotation.Nonnull String requestID) {
    this.requestID = requestID;
    return this;
  }

  /**
   * Get requestID
   * @return requestID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUEST_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestID() {
    return requestID;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestID(@jakarta.annotation.Nonnull String requestID) {
    this.requestID = requestID;
  }


  /**
   * Return true if this Event_question_rejected_properties object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventQuestionRejectedProperties eventQuestionRejectedProperties = (EventQuestionRejectedProperties) o;
    return Objects.equals(this.sessionID, eventQuestionRejectedProperties.sessionID) &&
        Objects.equals(this.requestID, eventQuestionRejectedProperties.requestID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionID, requestID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventQuestionRejectedProperties {\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    requestID: ").append(toIndentedString(requestID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sessionID` to the URL query string
    if (getSessionID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssessionID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSessionID()))));
    }

    // add `requestID` to the URL query string
    if (getRequestID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequestID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestID()))));
    }

    return joiner.toString();
  }
}

