/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * EventTuiCommandExecuteProperties
 */
@JsonPropertyOrder({
        EventTuiCommandExecuteProperties.JSON_PROPERTY_COMMAND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class EventTuiCommandExecuteProperties {
    public static final String JSON_PROPERTY_COMMAND = "command";
    @jakarta.annotation.Nonnull
    private EventTuiCommandExecutePropertiesCommand command;

    public EventTuiCommandExecuteProperties() {
    }

    public EventTuiCommandExecuteProperties command(@jakarta.annotation.Nonnull EventTuiCommandExecutePropertiesCommand command) {
        this.command = command;
        return this;
    }

    /**
     * Get command
     *
     * @return command
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public EventTuiCommandExecutePropertiesCommand getCommand() {
        return command;
    }


    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCommand(@jakarta.annotation.Nonnull EventTuiCommandExecutePropertiesCommand command) {
        this.command = command;
    }


    /**
     * Return true if this Event_tui_command_execute_properties object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventTuiCommandExecuteProperties eventTuiCommandExecuteProperties = (EventTuiCommandExecuteProperties) o;
        return Objects.equals(this.command, eventTuiCommandExecuteProperties.command);
    }

    @Override
    public int hashCode() {
        return Objects.hash(command);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EventTuiCommandExecuteProperties {\n");
        sb.append("    command: ").append(toIndentedString(command)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `command` to the URL query string
        if (getCommand() != null) {
            joiner.add(getCommand().toUrlQueryString(prefix + "command" + suffix));
        }

        return joiner.toString();
    }
}

