/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * EventCommandExecutedProperties
 */
@JsonPropertyOrder({
        EventCommandExecutedProperties.JSON_PROPERTY_NAME,
        EventCommandExecutedProperties.JSON_PROPERTY_SESSION_I_D,
        EventCommandExecutedProperties.JSON_PROPERTY_ARGUMENTS,
        EventCommandExecutedProperties.JSON_PROPERTY_MESSAGE_I_D
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class EventCommandExecutedProperties {
    public static final String JSON_PROPERTY_NAME = "name";
    @jakarta.annotation.Nonnull
    private String name;

    public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
    @jakarta.annotation.Nonnull
    private String sessionID;

    public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
    @jakarta.annotation.Nonnull
    private String arguments;

    public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
    @jakarta.annotation.Nonnull
    private String messageID;

    public EventCommandExecutedProperties() {
    }

    public EventCommandExecutedProperties name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getName() {
        return name;
    }


    @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }


    public EventCommandExecutedProperties sessionID(@jakarta.annotation.Nonnull String sessionID) {
        this.sessionID = sessionID;
        return this;
    }

    /**
     * Get sessionID
     *
     * @return sessionID
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getSessionID() {
        return sessionID;
    }


    @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
        this.sessionID = sessionID;
    }


    public EventCommandExecutedProperties arguments(@jakarta.annotation.Nonnull String arguments) {
        this.arguments = arguments;
        return this;
    }

    /**
     * Get arguments
     *
     * @return arguments
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getArguments() {
        return arguments;
    }


    @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setArguments(@jakarta.annotation.Nonnull String arguments) {
        this.arguments = arguments;
    }


    public EventCommandExecutedProperties messageID(@jakarta.annotation.Nonnull String messageID) {
        this.messageID = messageID;
        return this;
    }

    /**
     * Get messageID
     *
     * @return messageID
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getMessageID() {
        return messageID;
    }


    @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMessageID(@jakarta.annotation.Nonnull String messageID) {
        this.messageID = messageID;
    }


    /**
     * Return true if this Event_command_executed_properties object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventCommandExecutedProperties eventCommandExecutedProperties = (EventCommandExecutedProperties) o;
        return Objects.equals(this.name, eventCommandExecutedProperties.name) &&
                Objects.equals(this.sessionID, eventCommandExecutedProperties.sessionID) &&
                Objects.equals(this.arguments, eventCommandExecutedProperties.arguments) &&
                Objects.equals(this.messageID, eventCommandExecutedProperties.messageID);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, sessionID, arguments, messageID);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EventCommandExecutedProperties {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
        sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
        sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `name` to the URL query string
        if (getName() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
        }

        // add `sessionID` to the URL query string
        if (getSessionID() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%ssessionID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSessionID()))));
        }

        // add `arguments` to the URL query string
        if (getArguments() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sarguments%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getArguments()))));
        }

        // add `messageID` to the URL query string
        if (getMessageID() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smessageID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessageID()))));
        }

        return joiner.toString();
    }
}

