/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * ExperimentalWorkspaceCreateRequest
 */
@JsonPropertyOrder({
  ExperimentalWorkspaceCreateRequest.JSON_PROPERTY_ID,
  ExperimentalWorkspaceCreateRequest.JSON_PROPERTY_TYPE,
  ExperimentalWorkspaceCreateRequest.JSON_PROPERTY_BRANCH,
  ExperimentalWorkspaceCreateRequest.JSON_PROPERTY_EXTRA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ExperimentalWorkspaceCreateRequest {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_BRANCH = "branch";
  @jakarta.annotation.Nullable
  private String branch;

  public static final String JSON_PROPERTY_EXTRA = "extra";
  @jakarta.annotation.Nullable
  private Object extra;

  public ExperimentalWorkspaceCreateRequest() { 
  }

  public ExperimentalWorkspaceCreateRequest id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public ExperimentalWorkspaceCreateRequest type(@jakarta.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull String type) {
    this.type = type;
  }


  public ExperimentalWorkspaceCreateRequest branch(@jakarta.annotation.Nullable String branch) {
    this.branch = branch;
    return this;
  }

  /**
   * Get branch
   * @return branch
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRANCH, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBranch() {
    return branch;
  }


  @JsonProperty(value = JSON_PROPERTY_BRANCH, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBranch(@jakarta.annotation.Nullable String branch) {
    this.branch = branch;
  }


  public ExperimentalWorkspaceCreateRequest extra(@jakarta.annotation.Nullable Object extra) {
    this.extra = extra;
    return this;
  }

  /**
   * Get extra
   * @return extra
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTRA, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Object getExtra() {
    return extra;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTRA, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExtra(@jakarta.annotation.Nullable Object extra) {
    this.extra = extra;
  }


  /**
   * Return true if this experimental_workspace_create_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentalWorkspaceCreateRequest experimentalWorkspaceCreateRequest = (ExperimentalWorkspaceCreateRequest) o;
    return Objects.equals(this.id, experimentalWorkspaceCreateRequest.id) &&
        Objects.equals(this.type, experimentalWorkspaceCreateRequest.type) &&
        Objects.equals(this.branch, experimentalWorkspaceCreateRequest.branch) &&
        Objects.equals(this.extra, experimentalWorkspaceCreateRequest.extra);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, branch, extra);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentalWorkspaceCreateRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `branch` to the URL query string
    if (getBranch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbranch%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBranch()))));
    }

    // add `extra` to the URL query string
    // Note: extra is of type Object and doesn't support toUrlQueryString
    // Skipping URL query string serialization for this field

    return joiner.toString();
  }
}


