/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import opencode.sdk.invoker.JSON;

import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
@JsonDeserialize(using = FilePartSource.FilePartSourceDeserializer.class)
@JsonSerialize(using = FilePartSource.FilePartSourceSerializer.class)
public class FilePartSource extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(FilePartSource.class.getName());

    public static class FilePartSourceSerializer extends StdSerializer<FilePartSource> {
        public FilePartSourceSerializer(Class<FilePartSource> t) {
            super(t);
        }

        public FilePartSourceSerializer() {
            this(null);
        }

        @Override
        public void serialize(FilePartSource value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class FilePartSourceDeserializer extends StdDeserializer<FilePartSource> {
        public FilePartSourceDeserializer() {
            this(FilePartSource.class);
        }

        public FilePartSourceDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public FilePartSource deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize FileSource
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(FileSource.class);
                FilePartSource ret = new FilePartSource();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'FilePartSource'", e);
            }

            // deserialize ResourceSource
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(ResourceSource.class);
                FilePartSource ret = new FilePartSource();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'FilePartSource'", e);
            }

            // deserialize SymbolSource
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(SymbolSource.class);
                FilePartSource ret = new FilePartSource();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'FilePartSource'", e);
            }

            throw new IOException("Failed deserialization for FilePartSource: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public FilePartSource getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "FilePartSource cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public FilePartSource() {
        super("anyOf", Boolean.FALSE);
    }

    public FilePartSource(FileSource o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public FilePartSource(ResourceSource o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public FilePartSource(SymbolSource o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("FileSource", FileSource.class);
        schemas.put("ResourceSource", ResourceSource.class);
        schemas.put("SymbolSource", SymbolSource.class);
        JSON.registerDescendants(FilePartSource.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return FilePartSource.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * FileSource, ResourceSource, SymbolSource
     * <p>
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(FileSource.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ResourceSource.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SymbolSource.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be FileSource, ResourceSource, SymbolSource");
    }

    /**
     * Get the actual instance, which can be the following:
     * FileSource, ResourceSource, SymbolSource
     *
     * @return The actual instance (FileSource, ResourceSource, SymbolSource)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `FileSource`. If the actual instance is not `FileSource`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `FileSource`
     * @throws ClassCastException if the instance is not `FileSource`
     */
    public FileSource getFileSource() throws ClassCastException {
        return (FileSource) super.getActualInstance();
    }

    /**
     * Get the actual instance of `ResourceSource`. If the actual instance is not `ResourceSource`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ResourceSource`
     * @throws ClassCastException if the instance is not `ResourceSource`
     */
    public ResourceSource getResourceSource() throws ClassCastException {
        return (ResourceSource) super.getActualInstance();
    }

    /**
     * Get the actual instance of `SymbolSource`. If the actual instance is not `SymbolSource`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SymbolSource`
     * @throws ClassCastException if the instance is not `SymbolSource`
     */
    public SymbolSource getSymbolSource() throws ClassCastException {
        return (SymbolSource) super.getActualInstance();
    }


    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        return null;
    }

}

