/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * McpResource
 */
@JsonPropertyOrder({
  McpResource.JSON_PROPERTY_NAME,
  McpResource.JSON_PROPERTY_URI,
  McpResource.JSON_PROPERTY_DESCRIPTION,
  McpResource.JSON_PROPERTY_MIME_TYPE,
  McpResource.JSON_PROPERTY_CLIENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class McpResource {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_URI = "uri";
  @jakarta.annotation.Nonnull
  private String uri;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_MIME_TYPE = "mimeType";
  @jakarta.annotation.Nullable
  private String mimeType;

  public static final String JSON_PROPERTY_CLIENT = "client";
  @jakarta.annotation.Nonnull
  private String client;

  public McpResource() { 
  }

  public McpResource name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public McpResource uri(@jakarta.annotation.Nonnull String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   * @return uri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUri() {
    return uri;
  }


  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(@jakarta.annotation.Nonnull String uri) {
    this.uri = uri;
  }


  public McpResource description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public McpResource mimeType(@jakarta.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * Get mimeType
   * @return mimeType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMimeType() {
    return mimeType;
  }


  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMimeType(@jakarta.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
  }


  public McpResource client(@jakarta.annotation.Nonnull String client) {
    this.client = client;
    return this;
  }

  /**
   * Get client
   * @return client
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CLIENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClient() {
    return client;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClient(@jakarta.annotation.Nonnull String client) {
    this.client = client;
  }


  /**
   * Return true if this McpResource object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    McpResource mcpResource = (McpResource) o;
    return Objects.equals(this.name, mcpResource.name) &&
        Objects.equals(this.uri, mcpResource.uri) &&
        Objects.equals(this.description, mcpResource.description) &&
        Objects.equals(this.mimeType, mcpResource.mimeType) &&
        Objects.equals(this.client, mcpResource.client);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, uri, description, mimeType, client);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class McpResource {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `uri` to the URL query string
    if (getUri() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUri()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `mimeType` to the URL query string
    if (getMimeType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smimeType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMimeType()))));
    }

    // add `client` to the URL query string
    if (getClient() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclient%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClient()))));
    }

    return joiner.toString();
  }
}

