/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import opencode.sdk.model.AssistantMessageTokensCache;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * ModelCostExperimentalOver200K
 */
@JsonPropertyOrder({
  ModelCostExperimentalOver200K.JSON_PROPERTY_INPUT,
  ModelCostExperimentalOver200K.JSON_PROPERTY_OUTPUT,
  ModelCostExperimentalOver200K.JSON_PROPERTY_CACHE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ModelCostExperimentalOver200K {
  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nonnull
  private BigDecimal input;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @jakarta.annotation.Nonnull
  private BigDecimal output;

  public static final String JSON_PROPERTY_CACHE = "cache";
  @jakarta.annotation.Nonnull
  private AssistantMessageTokensCache cache;

  public ModelCostExperimentalOver200K() { 
  }

  public ModelCostExperimentalOver200K input(@jakarta.annotation.Nonnull BigDecimal input) {
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInput(@jakarta.annotation.Nonnull BigDecimal input) {
    this.input = input;
  }


  public ModelCostExperimentalOver200K output(@jakarta.annotation.Nonnull BigDecimal output) {
    this.output = output;
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getOutput() {
    return output;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutput(@jakarta.annotation.Nonnull BigDecimal output) {
    this.output = output;
  }


  public ModelCostExperimentalOver200K cache(@jakarta.annotation.Nonnull AssistantMessageTokensCache cache) {
    this.cache = cache;
    return this;
  }

  /**
   * Get cache
   * @return cache
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CACHE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AssistantMessageTokensCache getCache() {
    return cache;
  }


  @JsonProperty(value = JSON_PROPERTY_CACHE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCache(@jakarta.annotation.Nonnull AssistantMessageTokensCache cache) {
    this.cache = cache;
  }


  /**
   * Return true if this Model_cost_experimentalOver200K object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelCostExperimentalOver200K modelCostExperimentalOver200K = (ModelCostExperimentalOver200K) o;
    return Objects.equals(this.input, modelCostExperimentalOver200K.input) &&
        Objects.equals(this.output, modelCostExperimentalOver200K.output) &&
        Objects.equals(this.cache, modelCostExperimentalOver200K.cache);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, output, cache);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelCostExperimentalOver200K {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `input` to the URL query string
    if (getInput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInput()))));
    }

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soutput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutput()))));
    }

    // add `cache` to the URL query string
    if (getCache() != null) {
      joiner.add(getCache().toUrlQueryString(prefix + "cache" + suffix));
    }

    return joiner.toString();
  }
}

