/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import opencode.sdk.model.ModelCapabilitiesInput;
import opencode.sdk.model.ModelCapabilitiesInterleaved;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * ModelCapabilities
 */
@JsonPropertyOrder({
  ModelCapabilities.JSON_PROPERTY_TEMPERATURE,
  ModelCapabilities.JSON_PROPERTY_REASONING,
  ModelCapabilities.JSON_PROPERTY_ATTACHMENT,
  ModelCapabilities.JSON_PROPERTY_TOOLCALL,
  ModelCapabilities.JSON_PROPERTY_INPUT,
  ModelCapabilities.JSON_PROPERTY_OUTPUT,
  ModelCapabilities.JSON_PROPERTY_INTERLEAVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ModelCapabilities {
  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @jakarta.annotation.Nonnull
  private Boolean temperature;

  public static final String JSON_PROPERTY_REASONING = "reasoning";
  @jakarta.annotation.Nonnull
  private Boolean reasoning;

  public static final String JSON_PROPERTY_ATTACHMENT = "attachment";
  @jakarta.annotation.Nonnull
  private Boolean attachment;

  public static final String JSON_PROPERTY_TOOLCALL = "toolcall";
  @jakarta.annotation.Nonnull
  private Boolean toolcall;

  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nonnull
  private ModelCapabilitiesInput input;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @jakarta.annotation.Nonnull
  private ModelCapabilitiesInput output;

  public static final String JSON_PROPERTY_INTERLEAVED = "interleaved";
  @jakarta.annotation.Nonnull
  private ModelCapabilitiesInterleaved interleaved;

  public ModelCapabilities() { 
  }

  public ModelCapabilities temperature(@jakarta.annotation.Nonnull Boolean temperature) {
    this.temperature = temperature;
    return this;
  }

  /**
   * Get temperature
   * @return temperature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getTemperature() {
    return temperature;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemperature(@jakarta.annotation.Nonnull Boolean temperature) {
    this.temperature = temperature;
  }


  public ModelCapabilities reasoning(@jakarta.annotation.Nonnull Boolean reasoning) {
    this.reasoning = reasoning;
    return this;
  }

  /**
   * Get reasoning
   * @return reasoning
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASONING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getReasoning() {
    return reasoning;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReasoning(@jakarta.annotation.Nonnull Boolean reasoning) {
    this.reasoning = reasoning;
  }


  public ModelCapabilities attachment(@jakarta.annotation.Nonnull Boolean attachment) {
    this.attachment = attachment;
    return this;
  }

  /**
   * Get attachment
   * @return attachment
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ATTACHMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAttachment() {
    return attachment;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTACHMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttachment(@jakarta.annotation.Nonnull Boolean attachment) {
    this.attachment = attachment;
  }


  public ModelCapabilities toolcall(@jakarta.annotation.Nonnull Boolean toolcall) {
    this.toolcall = toolcall;
    return this;
  }

  /**
   * Get toolcall
   * @return toolcall
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOOLCALL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getToolcall() {
    return toolcall;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOLCALL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolcall(@jakarta.annotation.Nonnull Boolean toolcall) {
    this.toolcall = toolcall;
  }


  public ModelCapabilities input(@jakarta.annotation.Nonnull ModelCapabilitiesInput input) {
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelCapabilitiesInput getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInput(@jakarta.annotation.Nonnull ModelCapabilitiesInput input) {
    this.input = input;
  }


  public ModelCapabilities output(@jakarta.annotation.Nonnull ModelCapabilitiesInput output) {
    this.output = output;
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelCapabilitiesInput getOutput() {
    return output;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutput(@jakarta.annotation.Nonnull ModelCapabilitiesInput output) {
    this.output = output;
  }


  public ModelCapabilities interleaved(@jakarta.annotation.Nonnull ModelCapabilitiesInterleaved interleaved) {
    this.interleaved = interleaved;
    return this;
  }

  /**
   * Get interleaved
   * @return interleaved
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INTERLEAVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelCapabilitiesInterleaved getInterleaved() {
    return interleaved;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERLEAVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInterleaved(@jakarta.annotation.Nonnull ModelCapabilitiesInterleaved interleaved) {
    this.interleaved = interleaved;
  }


  /**
   * Return true if this Model_capabilities object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelCapabilities modelCapabilities = (ModelCapabilities) o;
    return Objects.equals(this.temperature, modelCapabilities.temperature) &&
        Objects.equals(this.reasoning, modelCapabilities.reasoning) &&
        Objects.equals(this.attachment, modelCapabilities.attachment) &&
        Objects.equals(this.toolcall, modelCapabilities.toolcall) &&
        Objects.equals(this.input, modelCapabilities.input) &&
        Objects.equals(this.output, modelCapabilities.output) &&
        Objects.equals(this.interleaved, modelCapabilities.interleaved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(temperature, reasoning, attachment, toolcall, input, output, interleaved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelCapabilities {\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    reasoning: ").append(toIndentedString(reasoning)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    toolcall: ").append(toIndentedString(toolcall)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    interleaved: ").append(toIndentedString(interleaved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `temperature` to the URL query string
    if (getTemperature() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemperature%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemperature()))));
    }

    // add `reasoning` to the URL query string
    if (getReasoning() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreasoning%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReasoning()))));
    }

    // add `attachment` to the URL query string
    if (getAttachment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sattachment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAttachment()))));
    }

    // add `toolcall` to the URL query string
    if (getToolcall() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoolcall%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToolcall()))));
    }

    // add `input` to the URL query string
    if (getInput() != null) {
      joiner.add(getInput().toUrlQueryString(prefix + "input" + suffix));
    }

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(getOutput().toUrlQueryString(prefix + "output" + suffix));
    }

    // add `interleaved` to the URL query string
    if (getInterleaved() != null) {
      joiner.add(getInterleaved().toUrlQueryString(prefix + "interleaved" + suffix));
    }

    return joiner.toString();
  }
}

