/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import opencode.sdk.model.ModelApi;
import opencode.sdk.model.ModelCapabilities;
import opencode.sdk.model.ModelCost;
import opencode.sdk.model.ProviderList200ResponseAllInnerModelsValueLimit;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * Model
 */
@JsonPropertyOrder({
  Model.JSON_PROPERTY_ID,
  Model.JSON_PROPERTY_PROVIDER_I_D,
  Model.JSON_PROPERTY_API,
  Model.JSON_PROPERTY_NAME,
  Model.JSON_PROPERTY_FAMILY,
  Model.JSON_PROPERTY_CAPABILITIES,
  Model.JSON_PROPERTY_COST,
  Model.JSON_PROPERTY_LIMIT,
  Model.JSON_PROPERTY_STATUS,
  Model.JSON_PROPERTY_OPTIONS,
  Model.JSON_PROPERTY_HEADERS,
  Model.JSON_PROPERTY_RELEASE_DATE,
  Model.JSON_PROPERTY_VARIANTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class Model {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_PROVIDER_I_D = "providerID";
  @jakarta.annotation.Nonnull
  private String providerID;

  public static final String JSON_PROPERTY_API = "api";
  @jakarta.annotation.Nonnull
  private ModelApi api;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_FAMILY = "family";
  @jakarta.annotation.Nullable
  private String family;

  public static final String JSON_PROPERTY_CAPABILITIES = "capabilities";
  @jakarta.annotation.Nonnull
  private ModelCapabilities capabilities;

  public static final String JSON_PROPERTY_COST = "cost";
  @jakarta.annotation.Nonnull
  private ModelCost cost;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nonnull
  private ProviderList200ResponseAllInnerModelsValueLimit limit;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ALPHA(String.valueOf("alpha")),
    
    BETA(String.valueOf("beta")),
    
    DEPRECATED(String.valueOf("deprecated")),
    
    ACTIVE(String.valueOf("active"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nonnull
  private Map<String, Object> options = new HashMap<>();

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nonnull
  private Map<String, String> headers = new HashMap<>();

  public static final String JSON_PROPERTY_RELEASE_DATE = "release_date";
  @jakarta.annotation.Nonnull
  private String releaseDate;

  public static final String JSON_PROPERTY_VARIANTS = "variants";
  @jakarta.annotation.Nullable
  private Map<String, Map<String, Object>> variants = new HashMap<>();

  public Model() { 
  }

  public Model id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public Model providerID(@jakarta.annotation.Nonnull String providerID) {
    this.providerID = providerID;
    return this;
  }

  /**
   * Get providerID
   * @return providerID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProviderID() {
    return providerID;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderID(@jakarta.annotation.Nonnull String providerID) {
    this.providerID = providerID;
  }


  public Model api(@jakarta.annotation.Nonnull ModelApi api) {
    this.api = api;
    return this;
  }

  /**
   * Get api
   * @return api
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_API, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelApi getApi() {
    return api;
  }


  @JsonProperty(value = JSON_PROPERTY_API, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApi(@jakarta.annotation.Nonnull ModelApi api) {
    this.api = api;
  }


  public Model name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public Model family(@jakarta.annotation.Nullable String family) {
    this.family = family;
    return this;
  }

  /**
   * Get family
   * @return family
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAMILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFamily() {
    return family;
  }


  @JsonProperty(value = JSON_PROPERTY_FAMILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFamily(@jakarta.annotation.Nullable String family) {
    this.family = family;
  }


  public Model capabilities(@jakarta.annotation.Nonnull ModelCapabilities capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  /**
   * Get capabilities
   * @return capabilities
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CAPABILITIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelCapabilities getCapabilities() {
    return capabilities;
  }


  @JsonProperty(value = JSON_PROPERTY_CAPABILITIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCapabilities(@jakarta.annotation.Nonnull ModelCapabilities capabilities) {
    this.capabilities = capabilities;
  }


  public Model cost(@jakarta.annotation.Nonnull ModelCost cost) {
    this.cost = cost;
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelCost getCost() {
    return cost;
  }


  @JsonProperty(value = JSON_PROPERTY_COST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCost(@jakarta.annotation.Nonnull ModelCost cost) {
    this.cost = cost;
  }


  public Model limit(@jakarta.annotation.Nonnull ProviderList200ResponseAllInnerModelsValueLimit limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ProviderList200ResponseAllInnerModelsValueLimit getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@jakarta.annotation.Nonnull ProviderList200ResponseAllInnerModelsValueLimit limit) {
    this.limit = limit;
  }


  public Model status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public Model options(@jakarta.annotation.Nonnull Map<String, Object> options) {
    this.options = options;
    return this;
  }

  public Model putOptionsItem(String key, Object optionsItem) {
    if (this.options == null) {
      this.options = new HashMap<>();
    }
    this.options.put(key, optionsItem);
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getOptions() {
    return options;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setOptions(@jakarta.annotation.Nonnull Map<String, Object> options) {
    this.options = options;
  }


  public Model headers(@jakarta.annotation.Nonnull Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public Model putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeaders(@jakarta.annotation.Nonnull Map<String, String> headers) {
    this.headers = headers;
  }


  public Model releaseDate(@jakarta.annotation.Nonnull String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

  /**
   * Get releaseDate
   * @return releaseDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RELEASE_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReleaseDate() {
    return releaseDate;
  }


  @JsonProperty(value = JSON_PROPERTY_RELEASE_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReleaseDate(@jakarta.annotation.Nonnull String releaseDate) {
    this.releaseDate = releaseDate;
  }


  public Model variants(@jakarta.annotation.Nullable Map<String, Map<String, Object>> variants) {
    this.variants = variants;
    return this;
  }

  public Model putVariantsItem(String key, Map<String, Object> variantsItem) {
    if (this.variants == null) {
      this.variants = new HashMap<>();
    }
    this.variants.put(key, variantsItem);
    return this;
  }

  /**
   * Get variants
   * @return variants
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Map<String, Object>> getVariants() {
    return variants;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariants(@jakarta.annotation.Nullable Map<String, Map<String, Object>> variants) {
    this.variants = variants;
  }


  /**
   * Return true if this Model object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model model = (Model) o;
    return Objects.equals(this.id, model.id) &&
        Objects.equals(this.providerID, model.providerID) &&
        Objects.equals(this.api, model.api) &&
        Objects.equals(this.name, model.name) &&
        Objects.equals(this.family, model.family) &&
        Objects.equals(this.capabilities, model.capabilities) &&
        Objects.equals(this.cost, model.cost) &&
        Objects.equals(this.limit, model.limit) &&
        Objects.equals(this.status, model.status) &&
        Objects.equals(this.options, model.options) &&
        Objects.equals(this.headers, model.headers) &&
        Objects.equals(this.releaseDate, model.releaseDate) &&
        Objects.equals(this.variants, model.variants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, providerID, api, name, family, capabilities, cost, limit, status, options, headers, releaseDate, variants);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    providerID: ").append(toIndentedString(providerID)).append("\n");
    sb.append("    api: ").append(toIndentedString(api)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    variants: ").append(toIndentedString(variants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `providerID` to the URL query string
    if (getProviderID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviderID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderID()))));
    }

    // add `api` to the URL query string
    if (getApi() != null) {
      joiner.add(getApi().toUrlQueryString(prefix + "api" + suffix));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `family` to the URL query string
    if (getFamily() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfamily%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFamily()))));
    }

    // add `capabilities` to the URL query string
    if (getCapabilities() != null) {
      joiner.add(getCapabilities().toUrlQueryString(prefix + "capabilities" + suffix));
    }

    // add `cost` to the URL query string
    if (getCost() != null) {
      joiner.add(getCost().toUrlQueryString(prefix + "cost" + suffix));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(getLimit().toUrlQueryString(prefix + "limit" + suffix));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `options` to the URL query string
    if (getOptions() != null) {
      for (String _key : getOptions().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%soptions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getOptions().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getOptions().get(_key)))));
      }
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    // add `release_date` to the URL query string
    if (getReleaseDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srelease_date%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReleaseDate()))));
    }

    // add `variants` to the URL query string
    if (getVariants() != null) {
      for (String _key : getVariants().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%svariants%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getVariants().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getVariants().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

