/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * OutputFormatJsonSchema
 */
@JsonPropertyOrder({
  OutputFormatJsonSchema.JSON_PROPERTY_TYPE,
  OutputFormatJsonSchema.JSON_PROPERTY_SCHEMA,
  OutputFormatJsonSchema.JSON_PROPERTY_RETRY_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class OutputFormatJsonSchema {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    JSON_SCHEMA(String.valueOf("json_schema"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  @jakarta.annotation.Nonnull
  private Map<String, Object> schema = new HashMap<>();

  public static final String JSON_PROPERTY_RETRY_COUNT = "retryCount";
  @jakarta.annotation.Nullable
  private Integer retryCount = 2;

  public OutputFormatJsonSchema() { 
  }

  public OutputFormatJsonSchema type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public OutputFormatJsonSchema schema(@jakarta.annotation.Nonnull Map<String, Object> schema) {
    this.schema = schema;
    return this;
  }

  public OutputFormatJsonSchema putSchemaItem(String key, Object schemaItem) {
    if (this.schema == null) {
      this.schema = new HashMap<>();
    }
    this.schema.put(key, schemaItem);
    return this;
  }

  /**
   * Get schema
   * @return schema
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getSchema() {
    return schema;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setSchema(@jakarta.annotation.Nonnull Map<String, Object> schema) {
    this.schema = schema;
  }


  public OutputFormatJsonSchema retryCount(@jakarta.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
    return this;
  }

  /**
   * Get retryCount
   * minimum: 0
   * maximum: 9007199254740991
   * @return retryCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRetryCount() {
    return retryCount;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetryCount(@jakarta.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
  }


  /**
   * Return true if this OutputFormatJsonSchema object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputFormatJsonSchema outputFormatJsonSchema = (OutputFormatJsonSchema) o;
    return Objects.equals(this.type, outputFormatJsonSchema.type) &&
        Objects.equals(this.schema, outputFormatJsonSchema.schema) &&
        Objects.equals(this.retryCount, outputFormatJsonSchema.retryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, schema, retryCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputFormatJsonSchema {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    retryCount: ").append(toIndentedString(retryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `schema` to the URL query string
    if (getSchema() != null) {
      for (String _key : getSchema().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sschema%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getSchema().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getSchema().get(_key)))));
      }
    }

    // add `retryCount` to the URL query string
    if (getRetryCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretryCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetryCount()))));
    }

    return joiner.toString();
  }
}

