/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import opencode.sdk.invoker.JSON;

import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
@JsonDeserialize(using = Part.PartDeserializer.class)
@JsonSerialize(using = Part.PartSerializer.class)
public class Part extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Part.class.getName());

    public static class PartSerializer extends StdSerializer<Part> {
        public PartSerializer(Class<Part> t) {
            super(t);
        }

        public PartSerializer() {
            this(null);
        }

        @Override
        public void serialize(Part value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PartDeserializer extends StdDeserializer<Part> {
        public PartDeserializer() {
            this(Part.class);
        }

        public PartDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public Part deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize AgentPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(AgentPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize CompactionPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(CompactionPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize FilePart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(FilePart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize PatchPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(PatchPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize ReasoningPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(ReasoningPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize RetryPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(RetryPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize SnapshotPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(SnapshotPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize StepFinishPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(StepFinishPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize StepStartPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(StepStartPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize SubtaskPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(SubtaskPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize TextPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(TextPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            // deserialize ToolPart
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(ToolPart.class);
                Part ret = new Part();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'Part'", e);
            }

            throw new IOException("Failed deserialization for Part: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public Part getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "Part cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public Part() {
        super("anyOf", Boolean.FALSE);
    }

    public Part(AgentPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(CompactionPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(FilePart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(PatchPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(ReasoningPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(RetryPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(SnapshotPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(StepFinishPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(StepStartPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(SubtaskPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(TextPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Part(ToolPart o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AgentPart", AgentPart.class);
        schemas.put("CompactionPart", CompactionPart.class);
        schemas.put("FilePart", FilePart.class);
        schemas.put("PatchPart", PatchPart.class);
        schemas.put("ReasoningPart", ReasoningPart.class);
        schemas.put("RetryPart", RetryPart.class);
        schemas.put("SnapshotPart", SnapshotPart.class);
        schemas.put("StepFinishPart", StepFinishPart.class);
        schemas.put("StepStartPart", StepStartPart.class);
        schemas.put("SubtaskPart", SubtaskPart.class);
        schemas.put("TextPart", TextPart.class);
        schemas.put("ToolPart", ToolPart.class);
        JSON.registerDescendants(Part.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return Part.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * AgentPart, CompactionPart, FilePart, PatchPart, ReasoningPart, RetryPart, SnapshotPart, StepFinishPart, StepStartPart, SubtaskPart, TextPart, ToolPart
     * <p>
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AgentPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CompactionPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(FilePart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PatchPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ReasoningPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(RetryPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SnapshotPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(StepFinishPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(StepStartPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SubtaskPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(TextPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ToolPart.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AgentPart, CompactionPart, FilePart, PatchPart, ReasoningPart, RetryPart, SnapshotPart, StepFinishPart, StepStartPart, SubtaskPart, TextPart, ToolPart");
    }

    /**
     * Get the actual instance, which can be the following:
     * AgentPart, CompactionPart, FilePart, PatchPart, ReasoningPart, RetryPart, SnapshotPart, StepFinishPart, StepStartPart, SubtaskPart, TextPart, ToolPart
     *
     * @return The actual instance (AgentPart, CompactionPart, FilePart, PatchPart, ReasoningPart, RetryPart, SnapshotPart, StepFinishPart, StepStartPart, SubtaskPart, TextPart, ToolPart)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AgentPart`. If the actual instance is not `AgentPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AgentPart`
     * @throws ClassCastException if the instance is not `AgentPart`
     */
    public AgentPart getAgentPart() throws ClassCastException {
        return (AgentPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `CompactionPart`. If the actual instance is not `CompactionPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CompactionPart`
     * @throws ClassCastException if the instance is not `CompactionPart`
     */
    public CompactionPart getCompactionPart() throws ClassCastException {
        return (CompactionPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `FilePart`. If the actual instance is not `FilePart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `FilePart`
     * @throws ClassCastException if the instance is not `FilePart`
     */
    public FilePart getFilePart() throws ClassCastException {
        return (FilePart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `PatchPart`. If the actual instance is not `PatchPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PatchPart`
     * @throws ClassCastException if the instance is not `PatchPart`
     */
    public PatchPart getPatchPart() throws ClassCastException {
        return (PatchPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `ReasoningPart`. If the actual instance is not `ReasoningPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ReasoningPart`
     * @throws ClassCastException if the instance is not `ReasoningPart`
     */
    public ReasoningPart getReasoningPart() throws ClassCastException {
        return (ReasoningPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `RetryPart`. If the actual instance is not `RetryPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RetryPart`
     * @throws ClassCastException if the instance is not `RetryPart`
     */
    public RetryPart getRetryPart() throws ClassCastException {
        return (RetryPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `SnapshotPart`. If the actual instance is not `SnapshotPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SnapshotPart`
     * @throws ClassCastException if the instance is not `SnapshotPart`
     */
    public SnapshotPart getSnapshotPart() throws ClassCastException {
        return (SnapshotPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `StepFinishPart`. If the actual instance is not `StepFinishPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `StepFinishPart`
     * @throws ClassCastException if the instance is not `StepFinishPart`
     */
    public StepFinishPart getStepFinishPart() throws ClassCastException {
        return (StepFinishPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `StepStartPart`. If the actual instance is not `StepStartPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `StepStartPart`
     * @throws ClassCastException if the instance is not `StepStartPart`
     */
    public StepStartPart getStepStartPart() throws ClassCastException {
        return (StepStartPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `SubtaskPart`. If the actual instance is not `SubtaskPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SubtaskPart`
     * @throws ClassCastException if the instance is not `SubtaskPart`
     */
    public SubtaskPart getSubtaskPart() throws ClassCastException {
        return (SubtaskPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `TextPart`. If the actual instance is not `TextPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TextPart`
     * @throws ClassCastException if the instance is not `TextPart`
     */
    public TextPart getTextPart() throws ClassCastException {
        return (TextPart) super.getActualInstance();
    }

    /**
     * Get the actual instance of `ToolPart`. If the actual instance is not `ToolPart`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ToolPart`
     * @throws ClassCastException if the instance is not `ToolPart`
     */
    public ToolPart getToolPart() throws ClassCastException {
        return (ToolPart) super.getActualInstance();
    }


    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        return null;
    }

}

