/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * Path
 */
@JsonPropertyOrder({
        Path.JSON_PROPERTY_HOME,
        Path.JSON_PROPERTY_STATE,
        Path.JSON_PROPERTY_CONFIG,
        Path.JSON_PROPERTY_WORKTREE,
        Path.JSON_PROPERTY_DIRECTORY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class Path {
    public static final String JSON_PROPERTY_HOME = "home";
    @jakarta.annotation.Nonnull
    private String home;

    public static final String JSON_PROPERTY_STATE = "state";
    @jakarta.annotation.Nonnull
    private String state;

    public static final String JSON_PROPERTY_CONFIG = "config";
    @jakarta.annotation.Nonnull
    private String config;

    public static final String JSON_PROPERTY_WORKTREE = "worktree";
    @jakarta.annotation.Nonnull
    private String worktree;

    public static final String JSON_PROPERTY_DIRECTORY = "directory";
    @jakarta.annotation.Nonnull
    private String directory;

    public Path() {
    }

    public Path home(@jakarta.annotation.Nonnull String home) {
        this.home = home;
        return this;
    }

    /**
     * Get home
     *
     * @return home
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_HOME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getHome() {
        return home;
    }


    @JsonProperty(value = JSON_PROPERTY_HOME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHome(@jakarta.annotation.Nonnull String home) {
        this.home = home;
    }


    public Path state(@jakarta.annotation.Nonnull String state) {
        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getState() {
        return state;
    }


    @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setState(@jakarta.annotation.Nonnull String state) {
        this.state = state;
    }


    public Path config(@jakarta.annotation.Nonnull String config) {
        this.config = config;
        return this;
    }

    /**
     * Get config
     *
     * @return config
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getConfig() {
        return config;
    }


    @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setConfig(@jakarta.annotation.Nonnull String config) {
        this.config = config;
    }


    public Path worktree(@jakarta.annotation.Nonnull String worktree) {
        this.worktree = worktree;
        return this;
    }

    /**
     * Get worktree
     *
     * @return worktree
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_WORKTREE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getWorktree() {
        return worktree;
    }


    @JsonProperty(value = JSON_PROPERTY_WORKTREE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setWorktree(@jakarta.annotation.Nonnull String worktree) {
        this.worktree = worktree;
    }


    public Path directory(@jakarta.annotation.Nonnull String directory) {
        this.directory = directory;
        return this;
    }

    /**
     * Get directory
     *
     * @return directory
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DIRECTORY, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getDirectory() {
        return directory;
    }


    @JsonProperty(value = JSON_PROPERTY_DIRECTORY, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDirectory(@jakarta.annotation.Nonnull String directory) {
        this.directory = directory;
    }


    /**
     * Return true if this Path object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Path path = (Path) o;
        return Objects.equals(this.home, path.home) &&
                Objects.equals(this.state, path.state) &&
                Objects.equals(this.config, path.config) &&
                Objects.equals(this.worktree, path.worktree) &&
                Objects.equals(this.directory, path.directory);
    }

    @Override
    public int hashCode() {
        return Objects.hash(home, state, config, worktree, directory);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Path {\n");
        sb.append("    home: ").append(toIndentedString(home)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    config: ").append(toIndentedString(config)).append("\n");
        sb.append("    worktree: ").append(toIndentedString(worktree)).append("\n");
        sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `home` to the URL query string
        if (getHome() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%shome%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHome()))));
        }

        // add `state` to the URL query string
        if (getState() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sstate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getState()))));
        }

        // add `config` to the URL query string
        if (getConfig() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sconfig%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConfig()))));
        }

        // add `worktree` to the URL query string
        if (getWorktree() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sworktree%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWorktree()))));
        }

        // add `directory` to the URL query string
        if (getDirectory() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdirectory%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDirectory()))));
        }

        return joiner.toString();
    }
}

