/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Map;
import opencode.sdk.model.PermissionActionConfig;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import opencode.sdk.invoker.ApiClient;
import opencode.sdk.invoker.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
@JsonDeserialize(using=PermissionRuleConfig.PermissionRuleConfigDeserializer.class)
@JsonSerialize(using = PermissionRuleConfig.PermissionRuleConfigSerializer.class)
public class PermissionRuleConfig extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PermissionRuleConfig.class.getName());

    public static class PermissionRuleConfigSerializer extends StdSerializer<PermissionRuleConfig> {
        public PermissionRuleConfigSerializer(Class<PermissionRuleConfig> t) {
            super(t);
        }

        public PermissionRuleConfigSerializer() {
            this(null);
        }

        @Override
        public void serialize(PermissionRuleConfig value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PermissionRuleConfigDeserializer extends StdDeserializer<PermissionRuleConfig> {
        public PermissionRuleConfigDeserializer() {
            this(PermissionRuleConfig.class);
        }

        public PermissionRuleConfigDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public PermissionRuleConfig deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize Map<String, PermissionActionConfig>
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(new com.fasterxml.jackson.core.type.TypeReference<Map<String, PermissionActionConfig>>() {});
                PermissionRuleConfig ret = new PermissionRuleConfig();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'PermissionRuleConfig'", e);
            }

            // deserialize PermissionActionConfig
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(PermissionActionConfig.class);
                PermissionRuleConfig ret = new PermissionRuleConfig();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'PermissionRuleConfig'", e);
            }

            throw new IOException("Failed deserialization for PermissionRuleConfig: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public PermissionRuleConfig getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "PermissionRuleConfig cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public PermissionRuleConfig() {
        super("anyOf", Boolean.FALSE);
    }

    public PermissionRuleConfig(Map<String, PermissionActionConfig> o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PermissionRuleConfig(PermissionActionConfig o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Map<String, PermissionActionConfig>", Map.class);
        schemas.put("PermissionActionConfig", PermissionActionConfig.class);
        JSON.registerDescendants(PermissionRuleConfig.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return PermissionRuleConfig.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * Map<String, PermissionActionConfig>, PermissionActionConfig
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Map.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PermissionActionConfig.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Map<String, PermissionActionConfig>, PermissionActionConfig");
    }

    /**
     * Get the actual instance, which can be the following:
     * Map<String, PermissionActionConfig>, PermissionActionConfig
     *
     * @return The actual instance (Map<String, PermissionActionConfig>, PermissionActionConfig)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Map<String, PermissionActionConfig>`. If the actual instance is not `Map<String, PermissionActionConfig>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Map<String, PermissionActionConfig>`
     * @throws ClassCastException if the instance is not `Map<String, PermissionActionConfig>`
     */
    @SuppressWarnings("unchecked")
    public Map<String, PermissionActionConfig> getMapStringPermissionActionConfig() throws ClassCastException {
        return (Map<String, PermissionActionConfig>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PermissionActionConfig`. If the actual instance is not `PermissionActionConfig`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PermissionActionConfig`
     * @throws ClassCastException if the instance is not `PermissionActionConfig`
     */
    public PermissionActionConfig getPermissionActionConfig() throws ClassCastException {
        return (PermissionActionConfig)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}

