/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.math.BigDecimal;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * ProviderList200ResponseAllInnerModelsValueCostContextOver200k
 */
@JsonPropertyOrder({
        ProviderList200ResponseAllInnerModelsValueCostContextOver200k.JSON_PROPERTY_INPUT,
        ProviderList200ResponseAllInnerModelsValueCostContextOver200k.JSON_PROPERTY_OUTPUT,
        ProviderList200ResponseAllInnerModelsValueCostContextOver200k.JSON_PROPERTY_CACHE_READ,
        ProviderList200ResponseAllInnerModelsValueCostContextOver200k.JSON_PROPERTY_CACHE_WRITE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ProviderList200ResponseAllInnerModelsValueCostContextOver200k {
    public static final String JSON_PROPERTY_INPUT = "input";
    @jakarta.annotation.Nonnull
    private BigDecimal input;

    public static final String JSON_PROPERTY_OUTPUT = "output";
    @jakarta.annotation.Nonnull
    private BigDecimal output;

    public static final String JSON_PROPERTY_CACHE_READ = "cache_read";
    @jakarta.annotation.Nullable
    private BigDecimal cacheRead;

    public static final String JSON_PROPERTY_CACHE_WRITE = "cache_write";
    @jakarta.annotation.Nullable
    private BigDecimal cacheWrite;

    public ProviderList200ResponseAllInnerModelsValueCostContextOver200k() {
    }

    public ProviderList200ResponseAllInnerModelsValueCostContextOver200k input(@jakarta.annotation.Nonnull BigDecimal input) {
        this.input = input;
        return this;
    }

    /**
     * Get input
     *
     * @return input
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public BigDecimal getInput() {
        return input;
    }


    @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setInput(@jakarta.annotation.Nonnull BigDecimal input) {
        this.input = input;
    }


    public ProviderList200ResponseAllInnerModelsValueCostContextOver200k output(@jakarta.annotation.Nonnull BigDecimal output) {
        this.output = output;
        return this;
    }

    /**
     * Get output
     *
     * @return output
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public BigDecimal getOutput() {
        return output;
    }


    @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setOutput(@jakarta.annotation.Nonnull BigDecimal output) {
        this.output = output;
    }


    public ProviderList200ResponseAllInnerModelsValueCostContextOver200k cacheRead(@jakarta.annotation.Nullable BigDecimal cacheRead) {
        this.cacheRead = cacheRead;
        return this;
    }

    /**
     * Get cacheRead
     *
     * @return cacheRead
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_CACHE_READ, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public BigDecimal getCacheRead() {
        return cacheRead;
    }


    @JsonProperty(value = JSON_PROPERTY_CACHE_READ, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCacheRead(@jakarta.annotation.Nullable BigDecimal cacheRead) {
        this.cacheRead = cacheRead;
    }


    public ProviderList200ResponseAllInnerModelsValueCostContextOver200k cacheWrite(@jakarta.annotation.Nullable BigDecimal cacheWrite) {
        this.cacheWrite = cacheWrite;
        return this;
    }

    /**
     * Get cacheWrite
     *
     * @return cacheWrite
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_CACHE_WRITE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public BigDecimal getCacheWrite() {
        return cacheWrite;
    }


    @JsonProperty(value = JSON_PROPERTY_CACHE_WRITE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCacheWrite(@jakarta.annotation.Nullable BigDecimal cacheWrite) {
        this.cacheWrite = cacheWrite;
    }


    /**
     * Return true if this provider_list_200_response_all_inner_models_value_cost_context_over_200k object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProviderList200ResponseAllInnerModelsValueCostContextOver200k providerList200ResponseAllInnerModelsValueCostContextOver200k = (ProviderList200ResponseAllInnerModelsValueCostContextOver200k) o;
        return Objects.equals(this.input, providerList200ResponseAllInnerModelsValueCostContextOver200k.input) &&
                Objects.equals(this.output, providerList200ResponseAllInnerModelsValueCostContextOver200k.output) &&
                Objects.equals(this.cacheRead, providerList200ResponseAllInnerModelsValueCostContextOver200k.cacheRead) &&
                Objects.equals(this.cacheWrite, providerList200ResponseAllInnerModelsValueCostContextOver200k.cacheWrite);
    }

    @Override
    public int hashCode() {
        return Objects.hash(input, output, cacheRead, cacheWrite);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProviderList200ResponseAllInnerModelsValueCostContextOver200k {\n");
        sb.append("    input: ").append(toIndentedString(input)).append("\n");
        sb.append("    output: ").append(toIndentedString(output)).append("\n");
        sb.append("    cacheRead: ").append(toIndentedString(cacheRead)).append("\n");
        sb.append("    cacheWrite: ").append(toIndentedString(cacheWrite)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `input` to the URL query string
        if (getInput() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sinput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInput()))));
        }

        // add `output` to the URL query string
        if (getOutput() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%soutput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutput()))));
        }

        // add `cache_read` to the URL query string
        if (getCacheRead() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%scache_read%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCacheRead()))));
        }

        // add `cache_write` to the URL query string
        if (getCacheWrite() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%scache_write%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCacheWrite()))));
        }

        return joiner.toString();
    }
}

