/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * ProviderAuthAuthorization
 */
@JsonPropertyOrder({
        ProviderAuthAuthorization.JSON_PROPERTY_URL,
        ProviderAuthAuthorization.JSON_PROPERTY_METHOD,
        ProviderAuthAuthorization.JSON_PROPERTY_INSTRUCTIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ProviderAuthAuthorization {
    public static final String JSON_PROPERTY_URL = "url";
    @jakarta.annotation.Nonnull
    private String url;

    /**
     * Gets or Sets method
     */
    public enum MethodEnum {
        AUTO(String.valueOf("auto")),

        CODE(String.valueOf("code"));

        private String value;

        MethodEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static MethodEnum fromValue(String value) {
            for (MethodEnum b : MethodEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_METHOD = "method";
    @jakarta.annotation.Nonnull
    private MethodEnum method;

    public static final String JSON_PROPERTY_INSTRUCTIONS = "instructions";
    @jakarta.annotation.Nonnull
    private String instructions;

    public ProviderAuthAuthorization() {
    }

    public ProviderAuthAuthorization url(@jakarta.annotation.Nonnull String url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     *
     * @return url
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_URL, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getUrl() {
        return url;
    }


    @JsonProperty(value = JSON_PROPERTY_URL, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUrl(@jakarta.annotation.Nonnull String url) {
        this.url = url;
    }


    public ProviderAuthAuthorization method(@jakarta.annotation.Nonnull MethodEnum method) {
        this.method = method;
        return this;
    }

    /**
     * Get method
     *
     * @return method
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public MethodEnum getMethod() {
        return method;
    }


    @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMethod(@jakarta.annotation.Nonnull MethodEnum method) {
        this.method = method;
    }


    public ProviderAuthAuthorization instructions(@jakarta.annotation.Nonnull String instructions) {
        this.instructions = instructions;
        return this;
    }

    /**
     * Get instructions
     *
     * @return instructions
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_INSTRUCTIONS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getInstructions() {
        return instructions;
    }


    @JsonProperty(value = JSON_PROPERTY_INSTRUCTIONS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setInstructions(@jakarta.annotation.Nonnull String instructions) {
        this.instructions = instructions;
    }


    /**
     * Return true if this ProviderAuthAuthorization object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProviderAuthAuthorization providerAuthAuthorization = (ProviderAuthAuthorization) o;
        return Objects.equals(this.url, providerAuthAuthorization.url) &&
                Objects.equals(this.method, providerAuthAuthorization.method) &&
                Objects.equals(this.instructions, providerAuthAuthorization.instructions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(url, method, instructions);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProviderAuthAuthorization {\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    method: ").append(toIndentedString(method)).append("\n");
        sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `url` to the URL query string
        if (getUrl() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
        }

        // add `method` to the URL query string
        if (getMethod() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
        }

        // add `instructions` to the URL query string
        if (getInstructions() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sinstructions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInstructions()))));
        }

        return joiner.toString();
    }
}

