/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import opencode.sdk.model.ProviderConfigModelsValueInterleavedAnyOf;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import opencode.sdk.invoker.ApiClient;
import opencode.sdk.invoker.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
@JsonDeserialize(using=ProviderConfigModelsValueInterleaved.ProviderConfigModelsValueInterleavedDeserializer.class)
@JsonSerialize(using = ProviderConfigModelsValueInterleaved.ProviderConfigModelsValueInterleavedSerializer.class)
public class ProviderConfigModelsValueInterleaved extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ProviderConfigModelsValueInterleaved.class.getName());

    public static class ProviderConfigModelsValueInterleavedSerializer extends StdSerializer<ProviderConfigModelsValueInterleaved> {
        public ProviderConfigModelsValueInterleavedSerializer(Class<ProviderConfigModelsValueInterleaved> t) {
            super(t);
        }

        public ProviderConfigModelsValueInterleavedSerializer() {
            this(null);
        }

        @Override
        public void serialize(ProviderConfigModelsValueInterleaved value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ProviderConfigModelsValueInterleavedDeserializer extends StdDeserializer<ProviderConfigModelsValueInterleaved> {
        public ProviderConfigModelsValueInterleavedDeserializer() {
            this(ProviderConfigModelsValueInterleaved.class);
        }

        public ProviderConfigModelsValueInterleavedDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ProviderConfigModelsValueInterleaved deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize Boolean
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(Boolean.class);
                ProviderConfigModelsValueInterleaved ret = new ProviderConfigModelsValueInterleaved();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ProviderConfigModelsValueInterleaved'", e);
            }

            // deserialize ProviderConfigModelsValueInterleavedAnyOf
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(ProviderConfigModelsValueInterleavedAnyOf.class);
                ProviderConfigModelsValueInterleaved ret = new ProviderConfigModelsValueInterleaved();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ProviderConfigModelsValueInterleaved'", e);
            }

            throw new IOException("Failed deserialization for ProviderConfigModelsValueInterleaved: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ProviderConfigModelsValueInterleaved getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "ProviderConfigModelsValueInterleaved cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public ProviderConfigModelsValueInterleaved() {
        super("anyOf", Boolean.FALSE);
    }

    public ProviderConfigModelsValueInterleaved(Boolean o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ProviderConfigModelsValueInterleaved(ProviderConfigModelsValueInterleavedAnyOf o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Boolean", Boolean.class);
        schemas.put("ProviderConfigModelsValueInterleavedAnyOf", ProviderConfigModelsValueInterleavedAnyOf.class);
        JSON.registerDescendants(ProviderConfigModelsValueInterleaved.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ProviderConfigModelsValueInterleaved.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * Boolean, ProviderConfigModelsValueInterleavedAnyOf
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Boolean.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ProviderConfigModelsValueInterleavedAnyOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Boolean, ProviderConfigModelsValueInterleavedAnyOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * Boolean, ProviderConfigModelsValueInterleavedAnyOf
     *
     * @return The actual instance (Boolean, ProviderConfigModelsValueInterleavedAnyOf)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Boolean`. If the actual instance is not `Boolean`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Boolean`
     * @throws ClassCastException if the instance is not `Boolean`
     */
    public Boolean getBoolean() throws ClassCastException {
        return (Boolean)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ProviderConfigModelsValueInterleavedAnyOf`. If the actual instance is not `ProviderConfigModelsValueInterleavedAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ProviderConfigModelsValueInterleavedAnyOf`
     * @throws ClassCastException if the instance is not `ProviderConfigModelsValueInterleavedAnyOf`
     */
    public ProviderConfigModelsValueInterleavedAnyOf getProviderConfigModelsValueInterleavedAnyOf() throws ClassCastException {
        return (ProviderConfigModelsValueInterleavedAnyOf)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}

