/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import opencode.sdk.model.QuestionOption;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * QuestionInfo
 */
@JsonPropertyOrder({
  QuestionInfo.JSON_PROPERTY_QUESTION,
  QuestionInfo.JSON_PROPERTY_HEADER,
  QuestionInfo.JSON_PROPERTY_OPTIONS,
  QuestionInfo.JSON_PROPERTY_MULTIPLE,
  QuestionInfo.JSON_PROPERTY_CUSTOM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class QuestionInfo {
  public static final String JSON_PROPERTY_QUESTION = "question";
  @jakarta.annotation.Nonnull
  private String question;

  public static final String JSON_PROPERTY_HEADER = "header";
  @jakarta.annotation.Nonnull
  private String header;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nonnull
  private List<QuestionOption> options = new ArrayList<>();

  public static final String JSON_PROPERTY_MULTIPLE = "multiple";
  @jakarta.annotation.Nullable
  private Boolean multiple;

  public static final String JSON_PROPERTY_CUSTOM = "custom";
  @jakarta.annotation.Nullable
  private Boolean custom;

  public QuestionInfo() { 
  }

  public QuestionInfo question(@jakarta.annotation.Nonnull String question) {
    this.question = question;
    return this;
  }

  /**
   * Complete question
   * @return question
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUESTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQuestion() {
    return question;
  }


  @JsonProperty(value = JSON_PROPERTY_QUESTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuestion(@jakarta.annotation.Nonnull String question) {
    this.question = question;
  }


  public QuestionInfo header(@jakarta.annotation.Nonnull String header) {
    this.header = header;
    return this;
  }

  /**
   * Very short label (max 30 chars)
   * @return header
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HEADER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHeader() {
    return header;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeader(@jakarta.annotation.Nonnull String header) {
    this.header = header;
  }


  public QuestionInfo options(@jakarta.annotation.Nonnull List<QuestionOption> options) {
    this.options = options;
    return this;
  }

  public QuestionInfo addOptionsItem(QuestionOption optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

  /**
   * Available choices
   * @return options
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<QuestionOption> getOptions() {
    return options;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptions(@jakarta.annotation.Nonnull List<QuestionOption> options) {
    this.options = options;
  }


  public QuestionInfo multiple(@jakarta.annotation.Nullable Boolean multiple) {
    this.multiple = multiple;
    return this;
  }

  /**
   * Allow selecting multiple choices
   * @return multiple
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MULTIPLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMultiple() {
    return multiple;
  }


  @JsonProperty(value = JSON_PROPERTY_MULTIPLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultiple(@jakarta.annotation.Nullable Boolean multiple) {
    this.multiple = multiple;
  }


  public QuestionInfo custom(@jakarta.annotation.Nullable Boolean custom) {
    this.custom = custom;
    return this;
  }

  /**
   * Allow typing a custom answer (default: true)
   * @return custom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCustom() {
    return custom;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustom(@jakarta.annotation.Nullable Boolean custom) {
    this.custom = custom;
  }


  /**
   * Return true if this QuestionInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuestionInfo questionInfo = (QuestionInfo) o;
    return Objects.equals(this.question, questionInfo.question) &&
        Objects.equals(this.header, questionInfo.header) &&
        Objects.equals(this.options, questionInfo.options) &&
        Objects.equals(this.multiple, questionInfo.multiple) &&
        Objects.equals(this.custom, questionInfo.custom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(question, header, options, multiple, custom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuestionInfo {\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    multiple: ").append(toIndentedString(multiple)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `question` to the URL query string
    if (getQuestion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squestion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuestion()))));
    }

    // add `header` to the URL query string
    if (getHeader() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sheader%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHeader()))));
    }

    // add `options` to the URL query string
    if (getOptions() != null) {
      for (int i = 0; i < getOptions().size(); i++) {
        if (getOptions().get(i) != null) {
          joiner.add(getOptions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%soptions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `multiple` to the URL query string
    if (getMultiple() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smultiple%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMultiple()))));
    }

    // add `custom` to the URL query string
    if (getCustom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustom()))));
    }

    return joiner.toString();
  }
}

