/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import opencode.sdk.model.SessionPromptRequestModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * SessionShellRequest
 */
@JsonPropertyOrder({
  SessionShellRequest.JSON_PROPERTY_AGENT,
  SessionShellRequest.JSON_PROPERTY_MODEL,
  SessionShellRequest.JSON_PROPERTY_COMMAND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class SessionShellRequest {
  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nonnull
  private String agent;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private SessionPromptRequestModel model;

  public static final String JSON_PROPERTY_COMMAND = "command";
  @jakarta.annotation.Nonnull
  private String command;

  public SessionShellRequest() { 
  }

  public SessionShellRequest agent(@jakarta.annotation.Nonnull String agent) {
    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgent(@jakarta.annotation.Nonnull String agent) {
    this.agent = agent;
  }


  public SessionShellRequest model(@jakarta.annotation.Nullable SessionPromptRequestModel model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SessionPromptRequestModel getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@jakarta.annotation.Nullable SessionPromptRequestModel model) {
    this.model = model;
  }


  public SessionShellRequest command(@jakarta.annotation.Nonnull String command) {
    this.command = command;
    return this;
  }

  /**
   * Get command
   * @return command
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCommand() {
    return command;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCommand(@jakarta.annotation.Nonnull String command) {
    this.command = command;
  }


  /**
   * Return true if this session_shell_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionShellRequest sessionShellRequest = (SessionShellRequest) o;
    return Objects.equals(this.agent, sessionShellRequest.agent) &&
        Objects.equals(this.model, sessionShellRequest.model) &&
        Objects.equals(this.command, sessionShellRequest.command);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, model, command);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionShellRequest {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `agent` to the URL query string
    if (getAgent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sagent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgent()))));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(getModel().toUrlQueryString(prefix + "model" + suffix));
    }

    // add `command` to the URL query string
    if (getCommand() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scommand%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommand()))));
    }

    return joiner.toString();
  }
}

