/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * SessionTime
 */
@JsonPropertyOrder({
  SessionTime.JSON_PROPERTY_CREATED,
  SessionTime.JSON_PROPERTY_UPDATED,
  SessionTime.JSON_PROPERTY_COMPACTING,
  SessionTime.JSON_PROPERTY_ARCHIVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class SessionTime {
  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nonnull
  private BigDecimal created;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @jakarta.annotation.Nonnull
  private BigDecimal updated;

  public static final String JSON_PROPERTY_COMPACTING = "compacting";
  @jakarta.annotation.Nullable
  private BigDecimal compacting;

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  @jakarta.annotation.Nullable
  private BigDecimal archived;

  public SessionTime() { 
  }

  public SessionTime created(@jakarta.annotation.Nonnull BigDecimal created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@jakarta.annotation.Nonnull BigDecimal created) {
    this.created = created;
  }


  public SessionTime updated(@jakarta.annotation.Nonnull BigDecimal updated) {
    this.updated = updated;
    return this;
  }

  /**
   * Get updated
   * @return updated
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getUpdated() {
    return updated;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdated(@jakarta.annotation.Nonnull BigDecimal updated) {
    this.updated = updated;
  }


  public SessionTime compacting(@jakarta.annotation.Nullable BigDecimal compacting) {
    this.compacting = compacting;
    return this;
  }

  /**
   * Get compacting
   * @return compacting
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPACTING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getCompacting() {
    return compacting;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPACTING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompacting(@jakarta.annotation.Nullable BigDecimal compacting) {
    this.compacting = compacting;
  }


  public SessionTime archived(@jakarta.annotation.Nullable BigDecimal archived) {
    this.archived = archived;
    return this;
  }

  /**
   * Get archived
   * @return archived
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARCHIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getArchived() {
    return archived;
  }


  @JsonProperty(value = JSON_PROPERTY_ARCHIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchived(@jakarta.annotation.Nullable BigDecimal archived) {
    this.archived = archived;
  }


  /**
   * Return true if this Session_time object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionTime sessionTime = (SessionTime) o;
    return Objects.equals(this.created, sessionTime.created) &&
        Objects.equals(this.updated, sessionTime.updated) &&
        Objects.equals(this.compacting, sessionTime.compacting) &&
        Objects.equals(this.archived, sessionTime.archived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, updated, compacting, archived);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionTime {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    compacting: ").append(toIndentedString(compacting)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreated()))));
    }

    // add `updated` to the URL query string
    if (getUpdated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdated()))));
    }

    // add `compacting` to the URL query string
    if (getCompacting() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompacting%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompacting()))));
    }

    // add `archived` to the URL query string
    if (getArchived() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sarchived%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getArchived()))));
    }

    return joiner.toString();
  }
}

