/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import opencode.sdk.model.FilePartSource;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import opencode.sdk.invoker.ApiClient;
/**
 * SessionCommandRequestPartsInner
 */
@JsonPropertyOrder({
  SessionCommandRequestPartsInner.JSON_PROPERTY_ID,
  SessionCommandRequestPartsInner.JSON_PROPERTY_TYPE,
  SessionCommandRequestPartsInner.JSON_PROPERTY_MIME,
  SessionCommandRequestPartsInner.JSON_PROPERTY_FILENAME,
  SessionCommandRequestPartsInner.JSON_PROPERTY_URL,
  SessionCommandRequestPartsInner.JSON_PROPERTY_SOURCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class SessionCommandRequestPartsInner {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    FILE(String.valueOf("file"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_MIME = "mime";
  @jakarta.annotation.Nonnull
  private String mime;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @jakarta.annotation.Nullable
  private String filename;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nullable
  private FilePartSource source;

  public SessionCommandRequestPartsInner() { 
  }

  public SessionCommandRequestPartsInner id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public SessionCommandRequestPartsInner type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public SessionCommandRequestPartsInner mime(@jakarta.annotation.Nonnull String mime) {
    this.mime = mime;
    return this;
  }

  /**
   * Get mime
   * @return mime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMime() {
    return mime;
  }


  @JsonProperty(value = JSON_PROPERTY_MIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMime(@jakarta.annotation.Nonnull String mime) {
    this.mime = mime;
  }


  public SessionCommandRequestPartsInner filename(@jakarta.annotation.Nullable String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Get filename
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFilename() {
    return filename;
  }


  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = filename;
  }


  public SessionCommandRequestPartsInner url(@jakarta.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }


  public SessionCommandRequestPartsInner source(@jakarta.annotation.Nullable FilePartSource source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FilePartSource getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@jakarta.annotation.Nullable FilePartSource source) {
    this.source = source;
  }


  /**
   * Return true if this session_command_request_parts_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionCommandRequestPartsInner sessionCommandRequestPartsInner = (SessionCommandRequestPartsInner) o;
    return Objects.equals(this.id, sessionCommandRequestPartsInner.id) &&
        Objects.equals(this.type, sessionCommandRequestPartsInner.type) &&
        Objects.equals(this.mime, sessionCommandRequestPartsInner.mime) &&
        Objects.equals(this.filename, sessionCommandRequestPartsInner.filename) &&
        Objects.equals(this.url, sessionCommandRequestPartsInner.url) &&
        Objects.equals(this.source, sessionCommandRequestPartsInner.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, mime, filename, url, source);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionCommandRequestPartsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `mime` to the URL query string
    if (getMime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMime()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(getSource().toUrlQueryString(prefix + "source" + suffix));
    }

    return joiner.toString();
  }
}

