/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * SessionCommandRequest
 */
@JsonPropertyOrder({
        SessionCommandRequest.JSON_PROPERTY_MESSAGE_I_D,
        SessionCommandRequest.JSON_PROPERTY_AGENT,
        SessionCommandRequest.JSON_PROPERTY_MODEL,
        SessionCommandRequest.JSON_PROPERTY_ARGUMENTS,
        SessionCommandRequest.JSON_PROPERTY_COMMAND,
        SessionCommandRequest.JSON_PROPERTY_VARIANT,
        SessionCommandRequest.JSON_PROPERTY_PARTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class SessionCommandRequest {
    public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
    @jakarta.annotation.Nullable
    private String messageID;

    public static final String JSON_PROPERTY_AGENT = "agent";
    @jakarta.annotation.Nullable
    private String agent;

    public static final String JSON_PROPERTY_MODEL = "model";
    @jakarta.annotation.Nullable
    private String model;

    public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
    @jakarta.annotation.Nonnull
    private String arguments;

    public static final String JSON_PROPERTY_COMMAND = "command";
    @jakarta.annotation.Nonnull
    private String command;

    public static final String JSON_PROPERTY_VARIANT = "variant";
    @jakarta.annotation.Nullable
    private String variant;

    public static final String JSON_PROPERTY_PARTS = "parts";
    @jakarta.annotation.Nullable
    private List<SessionCommandRequestPartsInner> parts = new ArrayList<>();

    public SessionCommandRequest() {
    }

    public SessionCommandRequest messageID(@jakarta.annotation.Nullable String messageID) {
        this.messageID = messageID;
        return this;
    }

    /**
     * Get messageID
     *
     * @return messageID
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMessageID() {
        return messageID;
    }


    @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMessageID(@jakarta.annotation.Nullable String messageID) {
        this.messageID = messageID;
    }


    public SessionCommandRequest agent(@jakarta.annotation.Nullable String agent) {
        this.agent = agent;
        return this;
    }

    /**
     * Get agent
     *
     * @return agent
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getAgent() {
        return agent;
    }


    @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAgent(@jakarta.annotation.Nullable String agent) {
        this.agent = agent;
    }


    public SessionCommandRequest model(@jakarta.annotation.Nullable String model) {
        this.model = model;
        return this;
    }

    /**
     * Get model
     *
     * @return model
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getModel() {
        return model;
    }


    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModel(@jakarta.annotation.Nullable String model) {
        this.model = model;
    }


    public SessionCommandRequest arguments(@jakarta.annotation.Nonnull String arguments) {
        this.arguments = arguments;
        return this;
    }

    /**
     * Get arguments
     *
     * @return arguments
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getArguments() {
        return arguments;
    }


    @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setArguments(@jakarta.annotation.Nonnull String arguments) {
        this.arguments = arguments;
    }


    public SessionCommandRequest command(@jakarta.annotation.Nonnull String command) {
        this.command = command;
        return this;
    }

    /**
     * Get command
     *
     * @return command
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getCommand() {
        return command;
    }


    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCommand(@jakarta.annotation.Nonnull String command) {
        this.command = command;
    }


    public SessionCommandRequest variant(@jakarta.annotation.Nullable String variant) {
        this.variant = variant;
        return this;
    }

    /**
     * Get variant
     *
     * @return variant
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getVariant() {
        return variant;
    }


    @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVariant(@jakarta.annotation.Nullable String variant) {
        this.variant = variant;
    }


    public SessionCommandRequest parts(@jakarta.annotation.Nullable List<SessionCommandRequestPartsInner> parts) {
        this.parts = parts;
        return this;
    }

    public SessionCommandRequest addPartsItem(SessionCommandRequestPartsInner partsItem) {
        if (this.parts == null) {
            this.parts = new ArrayList<>();
        }
        this.parts.add(partsItem);
        return this;
    }

    /**
     * Get parts
     *
     * @return parts
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_PARTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<SessionCommandRequestPartsInner> getParts() {
        return parts;
    }


    @JsonProperty(value = JSON_PROPERTY_PARTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParts(@jakarta.annotation.Nullable List<SessionCommandRequestPartsInner> parts) {
        this.parts = parts;
    }


    /**
     * Return true if this session_command_request object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SessionCommandRequest sessionCommandRequest = (SessionCommandRequest) o;
        return Objects.equals(this.messageID, sessionCommandRequest.messageID) &&
                Objects.equals(this.agent, sessionCommandRequest.agent) &&
                Objects.equals(this.model, sessionCommandRequest.model) &&
                Objects.equals(this.arguments, sessionCommandRequest.arguments) &&
                Objects.equals(this.command, sessionCommandRequest.command) &&
                Objects.equals(this.variant, sessionCommandRequest.variant) &&
                Objects.equals(this.parts, sessionCommandRequest.parts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(messageID, agent, model, arguments, command, variant, parts);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SessionCommandRequest {\n");
        sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
        sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
        sb.append("    command: ").append(toIndentedString(command)).append("\n");
        sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
        sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `messageID` to the URL query string
        if (getMessageID() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smessageID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessageID()))));
        }

        // add `agent` to the URL query string
        if (getAgent() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sagent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgent()))));
        }

        // add `model` to the URL query string
        if (getModel() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
        }

        // add `arguments` to the URL query string
        if (getArguments() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sarguments%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getArguments()))));
        }

        // add `command` to the URL query string
        if (getCommand() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%scommand%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommand()))));
        }

        // add `variant` to the URL query string
        if (getVariant() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%svariant%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVariant()))));
        }

        // add `parts` to the URL query string
        if (getParts() != null) {
            for (int i = 0; i < getParts().size(); i++) {
                if (getParts().get(i) != null) {
                    joiner.add(getParts().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sparts%s%s", prefix, suffix,
                            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
                }
            }
        }

        return joiner.toString();
    }
}

