/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.math.BigDecimal;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * SessionStatusAnyOf1
 */
@JsonPropertyOrder({
        SessionStatusAnyOf1.JSON_PROPERTY_TYPE,
        SessionStatusAnyOf1.JSON_PROPERTY_ATTEMPT,
        SessionStatusAnyOf1.JSON_PROPERTY_MESSAGE,
        SessionStatusAnyOf1.JSON_PROPERTY_NEXT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class SessionStatusAnyOf1 {
    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        RETRY(String.valueOf("retry"));

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_TYPE = "type";
    @jakarta.annotation.Nonnull
    private TypeEnum type;

    public static final String JSON_PROPERTY_ATTEMPT = "attempt";
    @jakarta.annotation.Nonnull
    private BigDecimal attempt;

    public static final String JSON_PROPERTY_MESSAGE = "message";
    @jakarta.annotation.Nonnull
    private String message;

    public static final String JSON_PROPERTY_NEXT = "next";
    @jakarta.annotation.Nonnull
    private BigDecimal next;

    public SessionStatusAnyOf1() {
    }

    public SessionStatusAnyOf1 type(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TypeEnum getType() {
        return type;
    }


    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
    }


    public SessionStatusAnyOf1 attempt(@jakarta.annotation.Nonnull BigDecimal attempt) {
        this.attempt = attempt;
        return this;
    }

    /**
     * Get attempt
     *
     * @return attempt
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_ATTEMPT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public BigDecimal getAttempt() {
        return attempt;
    }


    @JsonProperty(value = JSON_PROPERTY_ATTEMPT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAttempt(@jakarta.annotation.Nonnull BigDecimal attempt) {
        this.attempt = attempt;
    }


    public SessionStatusAnyOf1 message(@jakarta.annotation.Nonnull String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getMessage() {
        return message;
    }


    @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMessage(@jakarta.annotation.Nonnull String message) {
        this.message = message;
    }


    public SessionStatusAnyOf1 next(@jakarta.annotation.Nonnull BigDecimal next) {
        this.next = next;
        return this;
    }

    /**
     * Get next
     *
     * @return next
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_NEXT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public BigDecimal getNext() {
        return next;
    }


    @JsonProperty(value = JSON_PROPERTY_NEXT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNext(@jakarta.annotation.Nonnull BigDecimal next) {
        this.next = next;
    }


    /**
     * Return true if this SessionStatus_anyOf_1 object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SessionStatusAnyOf1 sessionStatusAnyOf1 = (SessionStatusAnyOf1) o;
        return Objects.equals(this.type, sessionStatusAnyOf1.type) &&
                Objects.equals(this.attempt, sessionStatusAnyOf1.attempt) &&
                Objects.equals(this.message, sessionStatusAnyOf1.message) &&
                Objects.equals(this.next, sessionStatusAnyOf1.next);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, attempt, message, next);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SessionStatusAnyOf1 {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    attempt: ").append(toIndentedString(attempt)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    next: ").append(toIndentedString(next)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
        }

        // add `attempt` to the URL query string
        if (getAttempt() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sattempt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAttempt()))));
        }

        // add `message` to the URL query string
        if (getMessage() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
        }

        // add `next` to the URL query string
        if (getNext() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%snext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNext()))));
        }

        return joiner.toString();
    }
}

