/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * SubtaskPartInput
 */
@JsonPropertyOrder({
        SubtaskPartInput.JSON_PROPERTY_ID,
        SubtaskPartInput.JSON_PROPERTY_TYPE,
        SubtaskPartInput.JSON_PROPERTY_PROMPT,
        SubtaskPartInput.JSON_PROPERTY_DESCRIPTION,
        SubtaskPartInput.JSON_PROPERTY_AGENT,
        SubtaskPartInput.JSON_PROPERTY_MODEL,
        SubtaskPartInput.JSON_PROPERTY_COMMAND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class SubtaskPartInput {
    public static final String JSON_PROPERTY_ID = "id";
    @jakarta.annotation.Nullable
    private String id;

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        SUBTASK(String.valueOf("subtask"));

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_TYPE = "type";
    @jakarta.annotation.Nonnull
    private TypeEnum type;

    public static final String JSON_PROPERTY_PROMPT = "prompt";
    @jakarta.annotation.Nonnull
    private String prompt;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    @jakarta.annotation.Nonnull
    private String description;

    public static final String JSON_PROPERTY_AGENT = "agent";
    @jakarta.annotation.Nonnull
    private String agent;

    public static final String JSON_PROPERTY_MODEL = "model";
    @jakarta.annotation.Nullable
    private SessionPromptRequestModel model;

    public static final String JSON_PROPERTY_COMMAND = "command";
    @jakarta.annotation.Nullable
    private String command;

    public SubtaskPartInput() {
    }

    public SubtaskPartInput id(@jakarta.annotation.Nullable String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_ID, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }


    @JsonProperty(value = JSON_PROPERTY_ID, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }


    public SubtaskPartInput type(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TypeEnum getType() {
        return type;
    }


    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
    }


    public SubtaskPartInput prompt(@jakarta.annotation.Nonnull String prompt) {
        this.prompt = prompt;
        return this;
    }

    /**
     * Get prompt
     *
     * @return prompt
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_PROMPT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getPrompt() {
        return prompt;
    }


    @JsonProperty(value = JSON_PROPERTY_PROMPT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPrompt(@jakarta.annotation.Nonnull String prompt) {
        this.prompt = prompt;
    }


    public SubtaskPartInput description(@jakarta.annotation.Nonnull String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getDescription() {
        return description;
    }


    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDescription(@jakarta.annotation.Nonnull String description) {
        this.description = description;
    }


    public SubtaskPartInput agent(@jakarta.annotation.Nonnull String agent) {
        this.agent = agent;
        return this;
    }

    /**
     * Get agent
     *
     * @return agent
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getAgent() {
        return agent;
    }


    @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAgent(@jakarta.annotation.Nonnull String agent) {
        this.agent = agent;
    }


    public SubtaskPartInput model(@jakarta.annotation.Nullable SessionPromptRequestModel model) {
        this.model = model;
        return this;
    }

    /**
     * Get model
     *
     * @return model
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public SessionPromptRequestModel getModel() {
        return model;
    }


    @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModel(@jakarta.annotation.Nullable SessionPromptRequestModel model) {
        this.model = model;
    }


    public SubtaskPartInput command(@jakarta.annotation.Nullable String command) {
        this.command = command;
        return this;
    }

    /**
     * Get command
     *
     * @return command
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getCommand() {
        return command;
    }


    @JsonProperty(value = JSON_PROPERTY_COMMAND, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCommand(@jakarta.annotation.Nullable String command) {
        this.command = command;
    }


    /**
     * Return true if this SubtaskPartInput object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubtaskPartInput subtaskPartInput = (SubtaskPartInput) o;
        return Objects.equals(this.id, subtaskPartInput.id) &&
                Objects.equals(this.type, subtaskPartInput.type) &&
                Objects.equals(this.prompt, subtaskPartInput.prompt) &&
                Objects.equals(this.description, subtaskPartInput.description) &&
                Objects.equals(this.agent, subtaskPartInput.agent) &&
                Objects.equals(this.model, subtaskPartInput.model) &&
                Objects.equals(this.command, subtaskPartInput.command);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, type, prompt, description, agent, model, command);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubtaskPartInput {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        sb.append("    command: ").append(toIndentedString(command)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `id` to the URL query string
        if (getId() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
        }

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
        }

        // add `prompt` to the URL query string
        if (getPrompt() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sprompt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrompt()))));
        }

        // add `description` to the URL query string
        if (getDescription() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
        }

        // add `agent` to the URL query string
        if (getAgent() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sagent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgent()))));
        }

        // add `model` to the URL query string
        if (getModel() != null) {
            joiner.add(getModel().toUrlQueryString(prefix + "model" + suffix));
        }

        // add `command` to the URL query string
        if (getCommand() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%scommand%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommand()))));
        }

        return joiner.toString();
    }
}

