/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.*;
import opencode.sdk.invoker.ApiClient;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * ToolStateRunning
 */
@JsonPropertyOrder({
        ToolStateRunning.JSON_PROPERTY_STATUS,
        ToolStateRunning.JSON_PROPERTY_INPUT,
        ToolStateRunning.JSON_PROPERTY_TITLE,
        ToolStateRunning.JSON_PROPERTY_METADATA,
        ToolStateRunning.JSON_PROPERTY_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class ToolStateRunning {
    /**
     * Gets or Sets status
     */
    public enum StatusEnum {
        RUNNING(String.valueOf("running"));

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_STATUS = "status";
    @jakarta.annotation.Nonnull
    private StatusEnum status;

    public static final String JSON_PROPERTY_INPUT = "input";
    @jakarta.annotation.Nonnull
    private Map<String, Object> input = new HashMap<>();

    public static final String JSON_PROPERTY_TITLE = "title";
    @jakarta.annotation.Nullable
    private String title;

    public static final String JSON_PROPERTY_METADATA = "metadata";
    @jakarta.annotation.Nullable
    private Map<String, Object> metadata = new HashMap<>();

    public static final String JSON_PROPERTY_TIME = "time";
    @jakarta.annotation.Nonnull
    private ToolStateRunningTime time;

    public ToolStateRunning() {
    }

    public ToolStateRunning status(@jakarta.annotation.Nonnull StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public StatusEnum getStatus() {
        return status;
    }


    @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
        this.status = status;
    }


    public ToolStateRunning input(@jakarta.annotation.Nonnull Map<String, Object> input) {
        this.input = input;
        return this;
    }

    public ToolStateRunning putInputItem(String key, Object inputItem) {
        if (this.input == null) {
            this.input = new HashMap<>();
        }
        this.input.put(key, inputItem);
        return this;
    }

    /**
     * Get input
     *
     * @return input
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
    public Map<String, Object> getInput() {
        return input;
    }


    @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
    public void setInput(@jakarta.annotation.Nonnull Map<String, Object> input) {
        this.input = input;
    }


    public ToolStateRunning title(@jakarta.annotation.Nullable String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTitle() {
        return title;
    }


    @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTitle(@jakarta.annotation.Nullable String title) {
        this.title = title;
    }


    public ToolStateRunning metadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
        this.metadata = metadata;
        return this;
    }

    public ToolStateRunning putMetadataItem(String key, Object metadataItem) {
        if (this.metadata == null) {
            this.metadata = new HashMap<>();
        }
        this.metadata.put(key, metadataItem);
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     */
    @jakarta.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, Object> getMetadata() {
        return metadata;
    }


    @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
        this.metadata = metadata;
    }


    public ToolStateRunning time(@jakarta.annotation.Nonnull ToolStateRunningTime time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     *
     * @return time
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public ToolStateRunningTime getTime() {
        return time;
    }


    @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTime(@jakarta.annotation.Nonnull ToolStateRunningTime time) {
        this.time = time;
    }


    /**
     * Return true if this ToolStateRunning object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ToolStateRunning toolStateRunning = (ToolStateRunning) o;
        return Objects.equals(this.status, toolStateRunning.status) &&
                Objects.equals(this.input, toolStateRunning.input) &&
                Objects.equals(this.title, toolStateRunning.title) &&
                Objects.equals(this.metadata, toolStateRunning.metadata) &&
                Objects.equals(this.time, toolStateRunning.time);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, input, title, metadata, time);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ToolStateRunning {\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    input: ").append(toIndentedString(input)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    time: ").append(toIndentedString(time)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `status` to the URL query string
        if (getStatus() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
        }

        // add `input` to the URL query string
        if (getInput() != null) {
            for (String _key : getInput().keySet()) {
                joiner.add(String.format(java.util.Locale.ROOT, "%sinput%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
                        getInput().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getInput().get(_key)))));
            }
        }

        // add `title` to the URL query string
        if (getTitle() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%stitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitle()))));
        }

        // add `metadata` to the URL query string
        if (getMetadata() != null) {
            for (String _key : getMetadata().keySet()) {
                joiner.add(String.format(java.util.Locale.ROOT, "%smetadata%s%s=%s", prefix, suffix,
                        "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
                        getMetadata().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getMetadata().get(_key)))));
            }
        }

        // add `time` to the URL query string
        if (getTime() != null) {
            joiner.add(getTime().toUrlQueryString(prefix + "time" + suffix));
        }

        return joiner.toString();
    }
}

