/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package opencode.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import opencode.sdk.invoker.ApiClient;

import java.math.BigDecimal;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * UserMessageTime
 */
@JsonPropertyOrder({
        UserMessageTime.JSON_PROPERTY_CREATED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T20:08:38.938506500+03:00[Europe/Minsk]", comments = "Generator version: 7.20.0")
public class UserMessageTime {
    public static final String JSON_PROPERTY_CREATED = "created";
    @jakarta.annotation.Nonnull
    private BigDecimal created;

    public UserMessageTime() {
    }

    public UserMessageTime created(@jakarta.annotation.Nonnull BigDecimal created) {
        this.created = created;
        return this;
    }

    /**
     * Get created
     *
     * @return created
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public BigDecimal getCreated() {
        return created;
    }


    @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCreated(@jakarta.annotation.Nonnull BigDecimal created) {
        this.created = created;
    }


    /**
     * Return true if this UserMessage_time object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserMessageTime userMessageTime = (UserMessageTime) o;
        return Objects.equals(this.created, userMessageTime.created);
    }

    @Override
    public int hashCode() {
        return Objects.hash(created);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserMessageTime {\n");
        sb.append("    created: ").append(toIndentedString(created)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `created` to the URL query string
        if (getCreated() != null) {
            joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreated()))));
        }

        return joiner.toString();
    }
}

